/*
 * ByteArrayDisplayPanel.java
 *
 * Created on October 26, 2008, 2:18 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import javax.swing.SwingUtilities;

/**
 *
 * @author  mike
 */
public class ByteArrayDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form ByteArrayDisplayPanel */
  public ByteArrayDisplayPanel()
  {
    initComponents();
  }

  public void setData(byte[] ba, Integer len)
  {
    int blen = ba.length;
    if(len != null)
      blen = len;
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < blen; i++) {
      sb.append(byteToHex(ba[i]));
    //sb.append(' ');  // included in ca
    }
    final int scrollBarValue = jScrollPane1.getVerticalScrollBar().getValue();
    jTextArea1.setText(sb.toString().trim());
    SwingUtilities.invokeLater(() -> {
        jScrollPane1.getVerticalScrollBar().setValue(scrollBarValue);
    });
  }
  private static char hChars[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
  private static char[] ca = {'0', '0', ' '};   // first 2 are continually replaced

  public static char[] byteToHex(byte by)
  {
    byte b = (byte) (by & 0xF0); // Strip off high nibble
    b = (byte) (b >>> 4);  // shift the bits down
    b = (byte) (b & 0x0F); // must do this if high order bit is on!
    ca[0] = hChars[(int) b];

    b = (byte) (by & 0x0F); // Strip off low nibble 
    ca[1] = hChars[(int) b];
    return ca;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
