/*
 * DesignatorPduDisplayPanel.java
 *
 * Created on October 26, 2008, 2:30 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import edu.nps.moves.dis7.pdus.DesignatorPdu;

import org.openide.util.NbBundle;

/**
 *
 * @author  mike
 */
public class DesignatorPduDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form DesignatorPduDisplayPanel */
  public DesignatorPduDisplayPanel()
  {
    initComponents();
  }

  public void setData(DesignatorPdu pdu)
  {
    pduHeaderDisplayPanel1.setData(pdu);
    designatingEntityIDDisplayPanel.setData(pdu.getDesignatingEntityID());
    codeNameTF.setText("" + pdu.getCodeName());
    designatedEntityIDDisplayPanel.setData(pdu.getDesignatedEntityID());

    desgCodeTF.setText(pdu.getDesignatorCode().getDescription());
    desgPowerTF.setText("" + pdu.getDesignatorPower());
    desgWavelengthTF.setText("" + pdu.getDesignatorWavelength());
    desgSpotTF.setText("" + pdu.getDesignatorSpotLocation());
    desgSpotRelativeTF.setText("" + pdu.getDesignatorSpotWrtDesignated());

    deadReckAlgoTF.setText(pdu.getDeadReckoningAlgorithm().getDescription());
    paddingTF.setText("" + pdu.getPadding1() + " " + pdu.getPadding2());
    entLinAccelTF.setText("" + pdu.getEntityLinearAcceleration().toString()); // test            
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    pduHeaderDisplayPanel1 = new org.web3d.x3d.dis.playerrecorder.PduHeaderDisplayPanel();
    designatingEntityIDDisplayPanel = new org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel();
    designatedEntityIDDisplayPanel = new org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel();
    jLabel2 = new javax.swing.JLabel();
    codeNameTF = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    desgCodeTF = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    desgPowerTF = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    desgWavelengthTF = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    desgSpotTF = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    desgSpotRelativeTF = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    deadReckAlgoTF = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    paddingTF = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    entLinAccelTF = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    pduHeaderDisplayPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PDU Header"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    add(pduHeaderDisplayPanel1, gridBagConstraints);

    designatingEntityIDDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Designating Entity"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    add(designatingEntityIDDisplayPanel, gridBagConstraints);

    designatedEntityIDDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Designated Entity"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(designatedEntityIDDisplayPanel, gridBagConstraints);

    jLabel2.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel2.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 3);
    add(jLabel2, gridBagConstraints);

    codeNameTF.setMinimumSize(new java.awt.Dimension(71, 22));
    codeNameTF.setPreferredSize(new java.awt.Dimension(71, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
    add(codeNameTF, gridBagConstraints);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Designator"));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel3.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel3.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(jLabel3, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(desgCodeTF, gridBagConstraints);

    jLabel4.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel4.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 3);
    jPanel1.add(jLabel4, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(desgPowerTF, gridBagConstraints);

    jLabel5.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel5.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 3);
    jPanel1.add(jLabel5, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(desgWavelengthTF, gridBagConstraints);

    jLabel6.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel6.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(jLabel6, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(desgSpotTF, gridBagConstraints);

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel10.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel10.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(jLabel10, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
    jPanel1.add(desgSpotRelativeTF, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
    add(jPanel1, gridBagConstraints);

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel7.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel7.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
    jPanel2.add(jLabel7, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel2.add(deadReckAlgoTF, gridBagConstraints);

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel8.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel8.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
    jPanel2.add(jLabel8, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
    jPanel2.add(paddingTF, gridBagConstraints);

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel9.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel9.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 3);
    jPanel2.add(jLabel9, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 3);
    jPanel2.add(entLinAccelTF, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    add(jPanel2, gridBagConstraints);

    jLabel1.setText(NbBundle.getMessage(getClass(), "DesignatorPduDisplayPanel.jLabel1.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jLabel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField codeNameTF;
  private javax.swing.JTextField deadReckAlgoTF;
  private javax.swing.JTextField desgCodeTF;
  private javax.swing.JTextField desgPowerTF;
  private javax.swing.JTextField desgSpotRelativeTF;
  private javax.swing.JTextField desgSpotTF;
  private javax.swing.JTextField desgWavelengthTF;
  private org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel designatedEntityIDDisplayPanel;
  private org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel designatingEntityIDDisplayPanel;
  private javax.swing.JTextField entLinAccelTF;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField paddingTF;
  private org.web3d.x3d.dis.playerrecorder.PduHeaderDisplayPanel pduHeaderDisplayPanel1;
  // End of variables declaration//GEN-END:variables
}
