/*
 * EntityStatePduDisplayPanel.java
 *
 * Created on October 26, 2008, 2:33 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import edu.nps.moves.dis7.pdus.EntityStatePdu;

import org.openide.util.NbBundle;

/**
 *
 * @author  mike
 */
public class EntityStatePduDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form EntityStatePduDisplayPanel */
  public EntityStatePduDisplayPanel()
  {
    initComponents();
  }

  public void setData(EntityStatePdu pdu)
  {
    this.altEntTypePanel.setData(pdu.getAlternativeEntityType());
    this.articulationParametersDisplayPanel1.setData(pdu.getVariableParameters().size(), pdu.getVariableParameters());
    this.deadReckoningPanel.setData(pdu.getDeadReckoningParameters());
    this.entityIDPanel.setData(pdu.getEntityID());
    this.entLinVelPanel.setData(pdu.getEntityLinearVelocity());
    this.entLocPanel.setData(pdu.getEntityLocation());
    this.entOrientationPanel.setData(pdu.getEntityOrientation());
    this.entityTypePanel.setData(pdu.getEntityType());
    this.markingPanel.setData(pdu.getMarking());

    // TODO lookup enumeration strings for clarity
    this.capTF.setText             ("" + pdu.getCapabilities());
    this.capTF.setToolTipText      ("" + pdu.getCapabilities());
    this.entAppearTF.setText       ("" + pdu.getEntityAppearance());
    this.entAppearTF.setToolTipText("" + pdu.getEntityAppearance());
    this.forceIDTF.setText         (pdu.getForceId().getDescription());
    this.forceIDTF.setToolTipText  ("" + pdu.getForceId() + " " + pdu.getForceId().getDescription());

    this.pduHeaderDisplayPanel1.setData(pdu);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pduHeaderDisplayPanel1 = new org.web3d.x3d.dis.playerrecorder.PduHeaderDisplayPanel();
        entityIDPanel = new org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel();
        entityTypePanel = new org.web3d.x3d.dis.playerrecorder.EntityTypeDisplayPanel();
        altEntTypePanel = new org.web3d.x3d.dis.playerrecorder.EntityTypeDisplayPanel();
        entLinVelPanel = new org.web3d.x3d.dis.playerrecorder.Vector3FloatDisplayPanel();
        entLocPanel = new org.web3d.x3d.dis.playerrecorder.Vector3DoubleDisplayPanel();
        entOrientationPanel = new org.web3d.x3d.dis.playerrecorder.OrientationRecordDisplayPanel();
        deadReckoningPanel = new org.web3d.x3d.dis.playerrecorder.DeadReckoningParameterDisplayPanel();
        markingPanel = new org.web3d.x3d.dis.playerrecorder.MarkingRecordDisplayPanel();
        jPanel1 = new javax.swing.JPanel();
        capabilitiesLabel = new javax.swing.JLabel();
        capTF = new javax.swing.JTextField();
        entityAppearanceLabel = new javax.swing.JLabel();
        entAppearTF = new javax.swing.JTextField();
        forceIDLabel = new javax.swing.JLabel();
        forceIDTF = new javax.swing.JTextField();
        articulationParametersDisplayPanel1 = new org.web3d.x3d.dis.playerrecorder.ArticulationParametersDisplayPanel();

        setLayout(new java.awt.GridBagLayout());

        pduHeaderDisplayPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PDU Header"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(pduHeaderDisplayPanel1, gridBagConstraints);

        entityIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity ID"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        add(entityIDPanel, gridBagConstraints);

        entityTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("EntityType"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(entityTypePanel, gridBagConstraints);

        altEntTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Alternative Entity Type"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(altEntTypePanel, gridBagConstraints);

        entLinVelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity Linear Velocity"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        add(entLinVelPanel, gridBagConstraints);

        entLocPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity Location"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        add(entLocPanel, gridBagConstraints);

        entOrientationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity Orientation"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(entOrientationPanel, gridBagConstraints);

        deadReckoningPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dead Reckoning Parameters"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(deadReckoningPanel, gridBagConstraints);

        markingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity Marking"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        add(markingPanel, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        capabilitiesLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        capabilitiesLabel.setText(NbBundle.getMessage(getClass(), "EntityStatePduDisplayPanel.capabilitiesLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(capabilitiesLabel, gridBagConstraints);

        capTF.setEditable(false);
        capTF.setForeground(new java.awt.Color(0, 102, 102));
        capTF.setMargin(new java.awt.Insets(2, 5, 3, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(capTF, gridBagConstraints);

        entityAppearanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        entityAppearanceLabel.setText(NbBundle.getMessage(getClass(), "EntityStatePduDisplayPanel.entityAppearanceLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(entityAppearanceLabel, gridBagConstraints);

        entAppearTF.setEditable(false);
        entAppearTF.setForeground(new java.awt.Color(0, 102, 102));
        entAppearTF.setMargin(new java.awt.Insets(2, 5, 3, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(entAppearTF, gridBagConstraints);

        forceIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        forceIDLabel.setText(NbBundle.getMessage(getClass(), "EntityStatePduDisplayPanel.forceIDLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(forceIDLabel, gridBagConstraints);

        forceIDTF.setEditable(false);
        forceIDTF.setForeground(new java.awt.Color(0, 102, 102));
        forceIDTF.setMargin(new java.awt.Insets(2, 5, 3, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(forceIDTF, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        articulationParametersDisplayPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Articulation Parameters"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(articulationParametersDisplayPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.web3d.x3d.dis.playerrecorder.EntityTypeDisplayPanel altEntTypePanel;
    private org.web3d.x3d.dis.playerrecorder.ArticulationParametersDisplayPanel articulationParametersDisplayPanel1;
    private javax.swing.JTextField capTF;
    private javax.swing.JLabel capabilitiesLabel;
    private org.web3d.x3d.dis.playerrecorder.DeadReckoningParameterDisplayPanel deadReckoningPanel;
    private javax.swing.JTextField entAppearTF;
    private org.web3d.x3d.dis.playerrecorder.Vector3FloatDisplayPanel entLinVelPanel;
    private org.web3d.x3d.dis.playerrecorder.Vector3DoubleDisplayPanel entLocPanel;
    private org.web3d.x3d.dis.playerrecorder.OrientationRecordDisplayPanel entOrientationPanel;
    private javax.swing.JLabel entityAppearanceLabel;
    private org.web3d.x3d.dis.playerrecorder.EntityIDDisplayPanel entityIDPanel;
    private org.web3d.x3d.dis.playerrecorder.EntityTypeDisplayPanel entityTypePanel;
    private javax.swing.JLabel forceIDLabel;
    private javax.swing.JTextField forceIDTF;
    private javax.swing.JPanel jPanel1;
    private org.web3d.x3d.dis.playerrecorder.MarkingRecordDisplayPanel markingPanel;
    private org.web3d.x3d.dis.playerrecorder.PduHeaderDisplayPanel pduHeaderDisplayPanel1;
    // End of variables declaration//GEN-END:variables
}
