/*
 * OrientationRecordDisplayPanel.java
 *
 * Created on October 26, 2008, 2:44 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import edu.nps.moves.dis7.pdus.EulerAngles;

import org.openide.util.NbBundle;

import static org.web3d.x3d.types.X3DPrimitiveTypes.*;

/**
 *
 * @author  mike
 */
public class OrientationRecordDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form OrientationRecordDisplayPanel */
  public OrientationRecordDisplayPanel()
  {
    initComponents();
  }

  public void setData(EulerAngles orientationRecord)
  {
             psiTF.setText(radiansFormat.format(orientationRecord.getPsi()) + " radians");
      psiDegreesTF.setText(degreesFormat.format(orientationRecord.getPsi()*180.0/Math.PI) + " degrees");
           thetaTF.setText(radiansFormat.format(orientationRecord.getTheta()) + " radians");
    thetaDegreesTF.setText(degreesFormat.format(orientationRecord.getTheta()*180.0/Math.PI) + " degrees");
             phiTF.setText(radiansFormat.format(orientationRecord.getPhi()) + " radians");
      phiDegreesTF.setText(degreesFormat.format(orientationRecord.getPhi()*180.0/Math.PI) + " degrees");
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        psiLabel = new javax.swing.JLabel();
        thetaLabel = new javax.swing.JLabel();
        phiLabel = new javax.swing.JLabel();
        psiTF = new javax.swing.JTextField();
        thetaTF = new javax.swing.JTextField();
        phiTF = new javax.swing.JTextField();
        phiDegreesTF = new javax.swing.JTextField();
        thetaDegreesTF = new javax.swing.JTextField();
        psiDegreesTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        psiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        psiLabel.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.psiLabel.text")); // NOI18N
        psiLabel.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.psiLabel.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(psiLabel, gridBagConstraints);

        thetaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        thetaLabel.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.thetaLabel.text")); // NOI18N
        thetaLabel.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.thetaLabel.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(thetaLabel, gridBagConstraints);

        phiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phiLabel.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.phiLabel.text")); // NOI18N
        phiLabel.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.phiLabel.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(phiLabel, gridBagConstraints);

        psiTF.setColumns(3);
        psiTF.setEditable(false);
        psiTF.setForeground(new java.awt.Color(0, 102, 102));
        psiTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psiTF.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.psiTF.text")); // NOI18N
        psiTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.psiTF.toolTipText")); // NOI18N
        psiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psiTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(psiTF, gridBagConstraints);

        thetaTF.setColumns(3);
        thetaTF.setEditable(false);
        thetaTF.setForeground(new java.awt.Color(0, 102, 102));
        thetaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        thetaTF.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.thetaTF.text")); // NOI18N
        thetaTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.thetaTF.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(thetaTF, gridBagConstraints);

        phiTF.setColumns(3);
        phiTF.setEditable(false);
        phiTF.setForeground(new java.awt.Color(0, 102, 102));
        phiTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phiTF.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.phiTF.text")); // NOI18N
        phiTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.phiTF.toolTipText")); // NOI18N
        phiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phiTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(phiTF, gridBagConstraints);

        phiDegreesTF.setColumns(3);
        phiDegreesTF.setEditable(false);
        phiDegreesTF.setForeground(new java.awt.Color(0, 102, 102));
        phiDegreesTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phiDegreesTF.setText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.phiDegreesTF.text")); // NOI18N
        phiDegreesTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.phiDegreesTF.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(phiDegreesTF, gridBagConstraints);

        thetaDegreesTF.setColumns(3);
        thetaDegreesTF.setEditable(false);
        thetaDegreesTF.setForeground(new java.awt.Color(0, 102, 102));
        thetaDegreesTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        thetaDegreesTF.setText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.thetaDegreesTF.text")); // NOI18N
        thetaDegreesTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.thetaDegreesTF.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(thetaDegreesTF, gridBagConstraints);

        psiDegreesTF.setColumns(3);
        psiDegreesTF.setEditable(false);
        psiDegreesTF.setForeground(new java.awt.Color(0, 102, 102));
        psiDegreesTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psiDegreesTF.setText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.psiDegreesTF.text")); // NOI18N
        psiDegreesTF.setToolTipText(org.openide.util.NbBundle.getMessage(OrientationRecordDisplayPanel.class, "OrientationRecordDisplayPanel.psiDegreesTF.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.166;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(psiDegreesTF, gridBagConstraints);

        jLabel1.setText(NbBundle.getMessage(getClass(), "OrientationRecordDisplayPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

  private void phiTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_phiTFActionPerformed
  {//GEN-HEADEREND:event_phiTFActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_phiTFActionPerformed

  private void psiTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_psiTFActionPerformed
  {//GEN-HEADEREND:event_psiTFActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_psiTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField phiDegreesTF;
    private javax.swing.JLabel phiLabel;
    private javax.swing.JTextField phiTF;
    private javax.swing.JTextField psiDegreesTF;
    private javax.swing.JLabel psiLabel;
    private javax.swing.JTextField psiTF;
    private javax.swing.JTextField thetaDegreesTF;
    private javax.swing.JLabel thetaLabel;
    private javax.swing.JTextField thetaTF;
    // End of variables declaration//GEN-END:variables
}
