/*
 * Vector3DoubleDisplayPanel.java
 *
 * Created on October 26, 2008, 3:04 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import edu.nps.moves.dis7.pdus.Vector3Double;
import org.openide.util.NbBundle;

/**
 *
 * @author  mike
 */
public class Vector3DoubleDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form Vector3DoubleDisplayPanel */
  public Vector3DoubleDisplayPanel()
  {
    initComponents();
  }

  public void setData(Vector3Double v)
  {
    xTF.setText("" + v.getX());
    yTF.setText("" + v.getY());
    zTF.setText("" + v.getZ());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        xTF = new javax.swing.JTextField();
        yTF = new javax.swing.JTextField();
        zTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        xTF.setEditable(false);
        xTF.setForeground(new java.awt.Color(0, 102, 102));
        xTF.setText(NbBundle.getMessage(getClass(), "Vector3DoubleDisplayPanel.xTF.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        add(xTF, gridBagConstraints);

        yTF.setEditable(false);
        yTF.setForeground(new java.awt.Color(0, 102, 102));
        yTF.setText(NbBundle.getMessage(getClass(), "Vector3DoubleDisplayPanel.yTF.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        add(yTF, gridBagConstraints);

        zTF.setEditable(false);
        zTF.setForeground(new java.awt.Color(0, 102, 102));
        zTF.setText(NbBundle.getMessage(getClass(), "Vector3DoubleDisplayPanel.zTF.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        add(zTF, gridBagConstraints);

        jLabel1.setText(NbBundle.getMessage(getClass(), "Vector3DoubleDisplayPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField xTF;
    private javax.swing.JTextField yTF;
    private javax.swing.JTextField zTF;
    // End of variables declaration//GEN-END:variables
}
