/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DSchemaData.*;

/**
 * COLLIDABLEOFFSETCustomizer.java
 * Created on 27 December 2008
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class COLLIDABLEOFFSETCustomizer extends BaseCustomizer
{
  private final COLLIDABLEOFFSET collidableOffset;
  private final JTextComponent target;
  
  /** Creates new form COLLIDABLEOFFSETCustomizer */
  public COLLIDABLEOFFSETCustomizer(COLLIDABLEOFFSET collidableOffset, JTextComponent target)
  {
    super(collidableOffset);
    this.collidableOffset = collidableOffset;
    this.target = target;
                             
    HelpCtx.setHelpIDString(this, "COLLIDABLEOFFSET_ELEM_HELPID");

    collidableOffset.setVisualizationSelectionAvailable(true); // must precede initComponents() interface initialization
    collidableOffset.setVisualizationTooltip("Add wireframe Box and axes to show boundingBox center and size (if defined)");
    
    initComponents();

    super.getDEFUSEpanel().setContainerFieldChoices(
            X3DNBodyCollidableNode_ATTR_CONTAINERFIELD_CHOICES, 
            X3DNBodyCollidableNode_ATTR_CONTAINERFIELD_TOOLTIPS);
    // DEFUSEpanel initialization must NOT be repeated or else array of choices will be overwritten
    
    enabledCB.setSelected(collidableOffset.isEnabled());
    
    bboxCenterXTF.setText(collidableOffset.getBboxCenterX());
    bboxCenterYTF.setText(collidableOffset.getBboxCenterY());
    bboxCenterZTF.setText(collidableOffset.getBboxCenterZ());
    bboxSizeXTF.setText(collidableOffset.getBboxSizeX());
    bboxSizeYTF.setText(collidableOffset.getBboxSizeY());
    bboxSizeZTF.setText(collidableOffset.getBboxSizeZ());
    rotation0TF.setText(collidableOffset.getRotation0());
    rotation1TF.setText(collidableOffset.getRotation1());
    rotation2TF.setText(collidableOffset.getRotation2());
    rotation3TF.setText(collidableOffset.getRotation3());
    translation0TF.setText(collidableOffset.getTranslation0());
    translation1TF.setText(collidableOffset.getTranslation1());
    translation2TF.setText(collidableOffset.getTranslation2());
  }

    private void checkVisualizable ()
    {
      enableAppendVisualizationCB(!(bboxSizeXTF.getText().equals("-1") && bboxSizeYTF.getText().equals("-1") && bboxSizeZTF.getText().equals("-1")));
    }
 
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        transLab = new javax.swing.JLabel();
        translation0TF = new javax.swing.JTextField();
        translation1TF = new javax.swing.JTextField();
        translation2TF = new javax.swing.JTextField();
        rotLab = new javax.swing.JLabel();
        rotation0TF = new javax.swing.JTextField();
        rotation1TF = new javax.swing.JTextField();
        rotation2TF = new javax.swing.JTextField();
        rotation3TF = new javax.swing.JTextField();
        bbCentLab = new javax.swing.JLabel();
        bboxCenterXTF = new javax.swing.JTextField();
        bboxCenterYTF = new javax.swing.JTextField();
        bboxCenterZTF = new javax.swing.JTextField();
        bboxSzLab = new javax.swing.JLabel();
        bboxSizeXTF = new javax.swing.JTextField();
        bboxSizeYTF = new javax.swing.JTextField();
        bboxSizeZTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enabledCB = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 3, 8);
        add(dEFUSEpanel1, gridBagConstraints);

        transLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        transLab.setText("translation");
        transLab.setToolTipText("Position (x, y, z in meters) of children relative to local coordinate system");
        transLab.setMinimumSize(new java.awt.Dimension(80, 22));
        transLab.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 3);
        add(transLab, gridBagConstraints);

        translation0TF.setColumns(4);
        translation0TF.setToolTipText("Position (x, y, z in meters) of children relative to local coordinate system");
        translation0TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(translation0TF, gridBagConstraints);

        translation1TF.setColumns(4);
        translation1TF.setToolTipText("Position (x, y, z in meters) of children relative to local coordinate system");
        translation1TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(translation1TF, gridBagConstraints);

        translation2TF.setColumns(4);
        translation2TF.setToolTipText("Position (x, y, z in meters) of children relative to local coordinate system");
        translation2TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(translation2TF, gridBagConstraints);

        rotLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rotLab.setText("rotation");
        rotLab.setToolTipText("Orientation (axis, angle in radians) of children relative to local coordinate system");
        rotLab.setMinimumSize(new java.awt.Dimension(80, 22));
        rotLab.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 3);
        add(rotLab, gridBagConstraints);

        rotation0TF.setColumns(4);
        rotation0TF.setToolTipText("Orientation (axis, angle in radians) of children relative to local coordinate system");
        rotation0TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(rotation0TF, gridBagConstraints);

        rotation1TF.setColumns(4);
        rotation1TF.setToolTipText("Orientation (axis, angle in radians) of children relative to local coordinate system");
        rotation1TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(rotation1TF, gridBagConstraints);

        rotation2TF.setColumns(4);
        rotation2TF.setToolTipText("Orientation (axis, angle in radians) of children relative to local coordinate system");
        rotation2TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(rotation2TF, gridBagConstraints);

        rotation3TF.setColumns(4);
        rotation3TF.setToolTipText("Orientation (axis, angle in radians) of children relative to local coordinate system");
        rotation3TF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 8);
        add(rotation3TF, gridBagConstraints);

        bbCentLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bbCentLab.setText("bboxCenter");
        bbCentLab.setToolTipText("position offset from origin of local coordinate system");
        bbCentLab.setMinimumSize(new java.awt.Dimension(80, 22));
        bbCentLab.setOpaque(true);
        bbCentLab.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 3);
        add(bbCentLab, gridBagConstraints);

        bboxCenterXTF.setColumns(4);
        bboxCenterXTF.setToolTipText("position offset from origin of local coordinate system");
        bboxCenterXTF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxCenterXTF, gridBagConstraints);

        bboxCenterYTF.setColumns(4);
        bboxCenterYTF.setToolTipText("position offset from origin of local coordinate system");
        bboxCenterYTF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxCenterYTF, gridBagConstraints);

        bboxCenterZTF.setColumns(4);
        bboxCenterZTF.setToolTipText("position offset from origin of local coordinate system");
        bboxCenterZTF.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxCenterZTF, gridBagConstraints);

        bboxSzLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bboxSzLab.setText("bboxSize");
        bboxSzLab.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        bboxSzLab.setMinimumSize(new java.awt.Dimension(80, 22));
        bboxSzLab.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 3);
        add(bboxSzLab, gridBagConstraints);

        bboxSizeXTF.setColumns(4);
        bboxSizeXTF.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        bboxSizeXTF.setMinimumSize(new java.awt.Dimension(50, 22));
        bboxSizeXTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboxSizeXTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxSizeXTF, gridBagConstraints);

        bboxSizeYTF.setColumns(4);
        bboxSizeYTF.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        bboxSizeYTF.setMinimumSize(new java.awt.Dimension(50, 22));
        bboxSizeYTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboxSizeYTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxSizeYTF, gridBagConstraints);

        bboxSizeZTF.setColumns(4);
        bboxSizeZTF.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        bboxSizeZTF.setMinimumSize(new java.awt.Dimension(50, 22));
        bboxSizeZTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboxSizeZTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bboxSizeZTF, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("enabled");
        jLabel2.setToolTipText("enable/disable node operation");
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 3);
        add(jLabel2, gridBagConstraints);

        enabledCB.setToolTipText("enable/disable node operation");
        enabledCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(enabledCB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bboxSizeXTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboxSizeXTFActionPerformed
        checkVisualizable ();
    }//GEN-LAST:event_bboxSizeXTFActionPerformed

    private void bboxSizeYTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboxSizeYTFActionPerformed
        checkVisualizable ();
    }//GEN-LAST:event_bboxSizeYTFActionPerformed

    private void bboxSizeZTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboxSizeZTFActionPerformed
        checkVisualizable ();
    }//GEN-LAST:event_bboxSizeZTFActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbCentLab;
    private javax.swing.JTextField bboxCenterXTF;
    private javax.swing.JTextField bboxCenterYTF;
    private javax.swing.JTextField bboxCenterZTF;
    private javax.swing.JTextField bboxSizeXTF;
    private javax.swing.JTextField bboxSizeYTF;
    private javax.swing.JTextField bboxSizeZTF;
    private javax.swing.JLabel bboxSzLab;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JCheckBox enabledCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel rotLab;
    private javax.swing.JTextField rotation0TF;
    private javax.swing.JTextField rotation1TF;
    private javax.swing.JTextField rotation2TF;
    private javax.swing.JTextField rotation3TF;
    private javax.swing.JLabel transLab;
    private javax.swing.JTextField translation0TF;
    private javax.swing.JTextField translation1TF;
    private javax.swing.JTextField translation2TF;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_COLLIDABLEOFFSET";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
    
    collidableOffset.setEnabled(enabledCB.isSelected());
    
    collidableOffset.setBboxCenterX(bboxCenterXTF.getText().trim());
    collidableOffset.setBboxCenterY(bboxCenterYTF.getText().trim());
    collidableOffset.setBboxCenterZ(bboxCenterZTF.getText().trim());
    collidableOffset.setBboxSizeX(bboxSizeXTF.getText().trim());
    collidableOffset.setBboxSizeY(bboxSizeYTF.getText().trim());
    collidableOffset.setBboxSizeZ(bboxSizeZTF.getText().trim());
    collidableOffset.setRotation0(rotation0TF.getText().trim());
    collidableOffset.setRotation1(rotation1TF.getText().trim());
    collidableOffset.setRotation2(rotation2TF.getText().trim());
    collidableOffset.setRotation3(rotation3TF.getText().trim());
    collidableOffset.setTranslation0(translation0TF.getText().trim());
    collidableOffset.setTranslation1(translation1TF.getText().trim());
    collidableOffset.setTranslation2(translation2TF.getText().trim());
  }   
}
