/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
/**
 * LOADSENSORCustomizer.java
 * Created on August 15, 2007, 2:25 PM
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey
 * @version $Id$
 */
public class LOADSENSORCustomizer extends BaseCustomizer
{
  private LOADSENSOR loadSensor;
  private JTextComponent target;
  
  /** Creates new form LOADSENSORCustomizer */
  public LOADSENSORCustomizer(LOADSENSOR loadSensor, JTextComponent target)
  {
    super(loadSensor);
    this.loadSensor = loadSensor;
    this.target = target;    
    
    HelpCtx.setHelpIDString(this, "LOADSENSOR_ELEM_HELPID");
    
    initComponents();

    enabledCB.setSelected(loadSensor.isEnabled());
    timeOutTF.setText(loadSensor.getTimeOut());
 }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        infoLabel = new javax.swing.JLabel();
        enabledCB = new javax.swing.JCheckBox();
        timeOutLabel = new javax.swing.JLabel();
        timeOutTF = new javax.swing.JTextField();
        spacerLabel = new javax.swing.JLabel();
        spacerLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        dEFUSEpanel1.setMinimumSize(new java.awt.Dimension(198, 77));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        infoLabel.setText(org.openide.util.NbBundle.getMessage(LOADSENSORCustomizer.class, "TextureBackgroundContentPanel.infoLabel.text")); // NOI18N
        infoLabel.setToolTipText(org.openide.util.NbBundle.getMessage(LOADSENSORCustomizer.class, "TextureBackgroundContentPanel.infoLabel.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(infoLabel, gridBagConstraints);

        enabledCB.setText("enabled");
        enabledCB.setToolTipText("enables/disables node operation");
        enabledCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        enabledCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledCB, gridBagConstraints);

        timeOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        timeOutLabel.setText("timeOut");
        timeOutLabel.setToolTipText("sends true on loading all watchList child nodes, otherwise false");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(timeOutLabel, gridBagConstraints);

        timeOutTF.setToolTipText("sends true on loading all watchList child nodes, otherwise false");
        timeOutTF.setMaximumSize(new java.awt.Dimension(80, 20));
        timeOutTF.setMinimumSize(new java.awt.Dimension(40, 20));
        timeOutTF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(timeOutTF, gridBagConstraints);

        spacerLabel.setText("                                        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(spacerLabel, gridBagConstraints);

        spacerLabel2.setText("          ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(spacerLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JCheckBox enabledCB;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JLabel spacerLabel2;
    private javax.swing.JLabel timeOutLabel;
    private javax.swing.JTextField timeOutTF;
    // End of variables declaration//GEN-END:variables

  public String getNameKey()
  {
    return "NAME_X3D_LOADSENSOR";
  }

  public void unloadInput() throws IllegalArgumentException
  {
    unLoadDEFUSE();

    loadSensor.setEnabled(enabledCB.isSelected());
    loadSensor.setTimeOut(timeOutTF.getText().trim());
  }  
}
