/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.awt.Color;
import javax.swing.text.JTextComponent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;
/**
 * POINTLIGHTCustomizer.java
 * Created on July 11, 2007, 5:13 PM
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey
 * @version $Id$
 */
public class POINTLIGHTCustomizer extends BaseCustomizer
{
  private POINTLIGHT pointLight;
  private JTextComponent target;
  
  /** Creates new form POINTLIGHTCustomizer */
  public POINTLIGHTCustomizer(POINTLIGHT pLight, JTextComponent target)
  {
    super(pLight);
    this.pointLight = pLight;
    this.target = target;
             
    HelpCtx.setHelpIDString(this, "POINTLIGHT_ELEM_HELPID");

    pointLight.setVisualizationSelectionAvailable(true); // must precede initComponents() interface initialization
    pointLight.setVisualizationTooltip("Add transparent Sphere for outer radius");
    
    initComponents();
    
    ambientIntensTF.setText(pLight.getAmbientIntensity());
    attenuation0TF.setText(pLight.getAttenuationX());
    attenuation1TF.setText(pLight.getAttenuationY());
    attenuation2TF.setText(pLight.getAttenuationZ());
    
    color0TF.setText(pLight.getColor0());
    color1TF.setText(pLight.getColor1());
    color2TF.setText(pLight.getColor2());

    bindColorChooserToBetterJTextFields(color0TF,color1TF,color2TF,colorChooser1);
   
    globalCB.setSelected(pLight.isGlobal());
    intensityTF.setText(pLight.getIntensity());
    location0TF.setText(pLight.getLocationX());
    location1TF.setText(pLight.getLocationY());
    location2TF.setText(pLight.getLocationZ());
    
    onCB.setSelected(pLight.isOn());
    radiusTF.setText(pLight.getRadius());
    checkRadius ();

    return;
  }

  private void checkRadius ()
  {
      if ((new SFFloat (radiusTF.getText())).getValue() < 0.0)
      {
          String message;
          message = "<html><center>Negative value provided for <b>radius</b> value, which is illegal.<br/><br/>Convert to default value <b>100</b> meters?";
          NotifyDescriptor descriptor = new NotifyDescriptor.Confirmation(
                  message, "radius must be zero or greater", NotifyDescriptor.YES_NO_OPTION);
          if (DialogDisplayer.getDefault().notify(descriptor) == NotifyDescriptor.YES_OPTION)
          {
              radiusTF.setText("100");
          }
      }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    dEFUSEpanel1 = getDEFUSEpanel();
    ambientIntensityLabel = new javax.swing.JLabel();
    ambientIntensTF = new javax.swing.JTextField();
    attenuationLabel = new javax.swing.JLabel();
    attenuation0TF = new javax.swing.JTextField();
    attenuation1TF = new javax.swing.JTextField();
    attenuation2TF = new javax.swing.JTextField();
    colorLabel = new javax.swing.JLabel();
    color0TF = new org.web3d.x3d.palette.BetterJTextField();
    color1TF = new org.web3d.x3d.palette.BetterJTextField();
    color2TF = new org.web3d.x3d.palette.BetterJTextField();
    intensityLabel = new javax.swing.JLabel();
    intensityTF = new javax.swing.JTextField();
    locationLabel = new javax.swing.JLabel();
    location0TF = new javax.swing.JTextField();
    location1TF = new javax.swing.JTextField();
    location2TF = new javax.swing.JTextField();
    globalLabel = new javax.swing.JLabel();
    globalCB = new javax.swing.JCheckBox();
    onLabel = new javax.swing.JLabel();
    onCB = new javax.swing.JCheckBox();
    colorChooser1 = new net.java.dev.colorchooser.ColorChooser();
    radiusLabel = new javax.swing.JLabel();
    radiusTF = new javax.swing.JTextField();
    spacerLabel = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(dEFUSEpanel1, gridBagConstraints);

    ambientIntensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    ambientIntensityLabel.setText("ambientIntensity");
    ambientIntensityLabel.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(ambientIntensityLabel, gridBagConstraints);

    ambientIntensTF.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
    ambientIntensTF.setMinimumSize(new java.awt.Dimension(60, 22));
    ambientIntensTF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(ambientIntensTF, gridBagConstraints);

    attenuationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    attenuationLabel.setText("attenuation");
    attenuationLabel.setToolTipText("constant, linear-distance and squared-distance dropoff factors");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(attenuationLabel, gridBagConstraints);

    attenuation0TF.setToolTipText("constant, linear-distance and squared-distance dropoff factors");
    attenuation0TF.setMinimumSize(new java.awt.Dimension(60, 22));
    attenuation0TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(attenuation0TF, gridBagConstraints);

    attenuation1TF.setToolTipText("constant, linear-distance and squared-distance dropoff factors");
    attenuation1TF.setMinimumSize(new java.awt.Dimension(60, 22));
    attenuation1TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(attenuation1TF, gridBagConstraints);

    attenuation2TF.setToolTipText("constant, linear-distance and squared-distance dropoff factors");
    attenuation2TF.setMinimumSize(new java.awt.Dimension(60, 22));
    attenuation2TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(attenuation2TF, gridBagConstraints);

    colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    colorLabel.setText("color");
    colorLabel.setToolTipText("color of light, applied to colors of objects");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(colorLabel, gridBagConstraints);

    color0TF.setToolTipText("color of light, applied to colors of objects");
    color0TF.setMinimumSize(new java.awt.Dimension(60, 22));
    color0TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(color0TF, gridBagConstraints);

    color1TF.setToolTipText("color of light, applied to colors of objects");
    color1TF.setMinimumSize(new java.awt.Dimension(60, 22));
    color1TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(color1TF, gridBagConstraints);

    color2TF.setToolTipText("color of light, applied to colors of objects");
    color2TF.setMinimumSize(new java.awt.Dimension(60, 22));
    color2TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(color2TF, gridBagConstraints);

    intensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    intensityLabel.setText("intensity");
    intensityLabel.setToolTipText("[0,1] brightness of direct light");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(intensityLabel, gridBagConstraints);

    intensityTF.setToolTipText("[0,1] brightness of direct light");
    intensityTF.setMinimumSize(new java.awt.Dimension(60, 22));
    intensityTF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(intensityTF, gridBagConstraints);

    locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    locationLabel.setText("location");
    locationLabel.setToolTipText("position of light relative to local coordinate system");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(locationLabel, gridBagConstraints);

    location0TF.setToolTipText("position of light relative to local coordinate system");
    location0TF.setMinimumSize(new java.awt.Dimension(60, 22));
    location0TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(location0TF, gridBagConstraints);

    location1TF.setToolTipText("position of light relative to local coordinate system");
    location1TF.setMinimumSize(new java.awt.Dimension(60, 22));
    location1TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(location1TF, gridBagConstraints);

    location2TF.setToolTipText("position of light relative to local coordinate system");
    location2TF.setMinimumSize(new java.awt.Dimension(60, 22));
    location2TF.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(location2TF, gridBagConstraints);

    globalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    globalLabel.setText("global");
    globalLabel.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(globalLabel, gridBagConstraints);

    globalCB.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
    globalCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
    globalCB.setMinimumSize(new java.awt.Dimension(60, 22));
    globalCB.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(globalCB, gridBagConstraints);

    onLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    onLabel.setText("on");
    onLabel.setToolTipText("enables/disables this light");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(onLabel, gridBagConstraints);

    onCB.setToolTipText("enables/disables this light");
    onCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
    onCB.setMinimumSize(new java.awt.Dimension(60, 22));
    onCB.setPreferredSize(new java.awt.Dimension(60, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(onCB, gridBagConstraints);

    colorChooser1.setMaximumSize(new java.awt.Dimension(22, 22));
    colorChooser1.setMinimumSize(new java.awt.Dimension(22, 22));
    colorChooser1.setPreferredSize(new java.awt.Dimension(22, 22));
    colorChooser1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        colorChooser1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout colorChooser1Layout = new javax.swing.GroupLayout(colorChooser1);
    colorChooser1.setLayout(colorChooser1Layout);
    colorChooser1Layout.setHorizontalGroup(
      colorChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );
    colorChooser1Layout.setVerticalGroup(
      colorChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(colorChooser1, gridBagConstraints);

    radiusLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    radiusLabel.setText("radius");
    radiusLabel.setToolTipText("maximum effective distance of light relative to local light position");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(radiusLabel, gridBagConstraints);

    radiusTF.setToolTipText("maximum effective distance of light relative to local light position");
    radiusTF.setMinimumSize(new java.awt.Dimension(60, 22));
    radiusTF.setPreferredSize(new java.awt.Dimension(60, 22));
    radiusTF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radiusTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(radiusTF, gridBagConstraints);

    spacerLabel.setText("        ");
    spacerLabel.setMaximumSize(null);
    spacerLabel.setMinimumSize(new java.awt.Dimension(10, 16));
    spacerLabel.setPreferredSize(new java.awt.Dimension(10, 16));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(spacerLabel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void colorChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooser1ActionPerformed
    Color c = colorChooser1.getColor();
    color0TF.setText(colorFormat.format((float)c.getRed()  /255.0f));
    color1TF.setText(colorFormat.format((float)c.getGreen()/255.0f));
    color2TF.setText(colorFormat.format((float)c.getBlue() /255.0f));
  }//GEN-LAST:event_colorChooser1ActionPerformed

  private void radiusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiusTFActionPerformed
      checkRadius ();
  }//GEN-LAST:event_radiusTFActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField ambientIntensTF;
  private javax.swing.JLabel ambientIntensityLabel;
  private javax.swing.JTextField attenuation0TF;
  private javax.swing.JTextField attenuation1TF;
  private javax.swing.JTextField attenuation2TF;
  private javax.swing.JLabel attenuationLabel;
  private org.web3d.x3d.palette.BetterJTextField color0TF;
  private org.web3d.x3d.palette.BetterJTextField color1TF;
  private org.web3d.x3d.palette.BetterJTextField color2TF;
  private net.java.dev.colorchooser.ColorChooser colorChooser1;
  private javax.swing.JLabel colorLabel;
  private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
  private javax.swing.JCheckBox globalCB;
  private javax.swing.JLabel globalLabel;
  private javax.swing.JLabel intensityLabel;
  private javax.swing.JTextField intensityTF;
  private javax.swing.JTextField location0TF;
  private javax.swing.JTextField location1TF;
  private javax.swing.JTextField location2TF;
  private javax.swing.JLabel locationLabel;
  private javax.swing.JCheckBox onCB;
  private javax.swing.JLabel onLabel;
  private javax.swing.JLabel radiusLabel;
  private javax.swing.JTextField radiusTF;
  private javax.swing.JLabel spacerLabel;
  // End of variables declaration//GEN-END:variables

  public String getNameKey()
  {
    return "NAME_X3D_POINTLIGHT";
  }

  public void unloadInput()
  {
    unLoadDEFUSE();
     
    pointLight.setAmbientIntensity(ambientIntensTF.getText().trim());
    pointLight.setAttenuationX(attenuation0TF.getText().trim());
    pointLight.setAttenuationY(attenuation1TF.getText().trim());
    pointLight.setAttenuationZ(attenuation2TF.getText().trim());
    
    pointLight.setColor0(color0TF.getText().trim());
    pointLight.setColor1(color1TF.getText().trim());
    pointLight.setColor2(color2TF.getText().trim());
    
    pointLight.setGlobal(globalCB.isSelected());
    
    pointLight.setIntensity(intensityTF.getText().trim());
    pointLight.setLocationX(location0TF.getText().trim());
    pointLight.setLocationY(location1TF.getText().trim());
    pointLight.setLocationZ(location2TF.getText().trim());
    
    pointLight.setOn(onCB.isSelected());
    checkRadius ();
    pointLight.setRadius(radiusTF.getText().trim());
  }
  
}
