/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import org.web3d.x3d.types.SceneGraphStructureNodeType;

/**
 * SMAL_VehicleMetadataTemplate.java
 * Created on 17 October 2009
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Don Brutzman, Mike Bailey
 * @version $Id$
 */
public class SMAL_VehicleMetadataTemplate extends SceneGraphStructureNodeType
{
  public SMAL_VehicleMetadataTemplate()
  {
  }

  @Override
  public void initialize()
  {
  }

  @Override
  public String createBody()
  {
    return "\n" +
            "    <!-- ==================== -->\n" +
            "    <WorldInfo info='\"https://savage.nps.edu/Savage/Tools/SMAL/SavageVehicleMetadataTemplate.x3d\"' title='SavageVehicleMetadataTemplate'>\n" +
            "      <MetadataSet containerField='metadata' name='SMAL' reference='https://savage.nps.edu/Savage/Tools/SMAL/SMAL.html'>\n" +
            "        <MetadataString containerField='value' name='version' value='1.0'>\n" +
            "          <MetadataString name='appinfo' value='This attribute is the SMAL version, not the model version.'/>\n" +
            "        </MetadataString>\n" +
            "        <MetadataSet containerField='value' name='EntityDefinition'>\n" +
            "          <!-- Identifying metadata for the current simulation of interest -->\n" +
            "          <MetadataSet containerField='value' name='Classification'>\n" +
            "            <MetadataString containerField='value' name='level' value='UNCLASSIFIED'>\n" +
            "              <MetadataString name='appinfo' value='UNCLASSIFIED, FOUO, CONFIDENTIAL, SECRET, or TOPSECRET'/>\n" +
            "            </MetadataString>\n" +
            "            <MetadataString containerField='value' name='reference'>\n" +
            "              <MetadataString name='appinfo' value='The published source of classified information, if any, contained in the Metadata.'/>\n" +
            "            </MetadataString>\n" +
            "            <MetadataString containerField='value' name='rationale'>\n" +
            "              <MetadataString name='appinfo' value='The specific element which contains the information classifying this document.'/>\n" +
            "            </MetadataString>\n" +
            "          </MetadataSet>\n" +
            "          <MetadataSet containerField='value' name='IdentificationParameters'>\n" +
            "            <MetadataString containerField='value' name='name' value='provideVehicleName'>\n" +
            "              <MetadataString name='appinfo' value='The plain language name of the vehicle this model represents, i.e. the base class (DDG-51), or vehicle designation (M1A2).'/>\n" +
            "            </MetadataString>\n" +
            "          </MetadataSet>\n" +
            "          <MetadataSet containerField='value' name='X3DArchiveModel'>\n" +
            "            <MetadataString name='appinfo' value='This is a placeholder element which ensures the proper validation of autogenerated SMAL code.'/>\n" +
            "          </MetadataSet>\n" +
            "          <MetadataSet containerField='value' name='PhysicalParameters'>\n" +
            "            <MetadataSet containerField='value' name='PhysicalConstraints'>\n" +
            "              <MetadataFloat containerField='value' name='height' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum structural height of the object in meters. This may be used for clearance checking or other calculations.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='width' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum width, beam, or wingspan of the vehicle in meters. This may be used for clearance checking or other calculations.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='length' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum structural length of the object in meters. This may be used for clearance checking or other calculations.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='draft' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The vertical distance in meters from the deepest point (keel or other structure) to the waterline of a vehicle at its stated displacement or gross weight.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='wheelbase' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The longitudinal distance in meters from the center of the forwardmost roadwheel axle to the center of the rearmost roadwheel axle on this vehicle.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='trackWidth' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The horizontal distance in meters from the rightmost edge of the right wheel or track to the leftmost edge of the left wheel or track on this vehicle.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='grossWeight' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The standard operational weight of the vehicle in pounds or kilograms. This may be used in any number of physics calculations.'/>\n" +
            "              </MetadataFloat>\n" +
            "            </MetadataSet>\n" +
            "            <MetadataSet containerField='value' name='DynamicResponseConstraints'>\n" +
            "              <MetadataFloat containerField='value' name='centerOfGravity' value='0 0 0'>\n" +
            "                <MetadataString name='appinfo' value='Sets the Center of Gravity of the object as an (x, y, z) distance in meters from the physical center of the object, which is located at (0, 0, 0).'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='aerodynamicCenter' value='0 0 0'>\n" +
            "                <MetadataString name='appinfo' value='Sets the Aerodynamic Center of the object as an (x, y, z) distance in meters from the physical center of the object, which is located at (0, 0, 0).'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='centerOfBuoyancy' value='0 0 0'>\n" +
            "                <MetadataString name='appinfo' value='Sets the Center of Buoyancy of the object as an (x, y, z) distance in meters from the physical center of the object, which is ocated at (0, 0, 0).'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumSpeed' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum rated speed for this vehicle in mph or kph.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='cruiseSpeed' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The published cruise speed for this vehicle in mph or kph.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumAltitude' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The absolute ceiling for this aircraft in feet or meters.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='cruiseAltitude' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The cruise ceiling for this aircraft in feet or meters.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumDepth' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The absolute depth for this submersible in feet or meters.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='cruiseDepth' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The cruise depth for this submersible in feet or meters.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumAcceleration' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The ideal maximum acceleration acheivable by this vehicle in feet or meters per second squared, as in at maximum Power excess for aircraft.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumDeceleration' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The ideal best braking performance acheivable by this vehicle in feet or meters per second squared.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='minimumTurnRadius' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The minimum turning radius for this vehicle in feet or meters, as in at best cornering speed for aircraft.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumTurnRate' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum turning rate for this vehicle in degrees per second, as in at best cornering speed for aircraft.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumFuelCapacity' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum usable internal fuel capacity of this vehicle in liters.'/>\n" +
            "              </MetadataFloat>\n" +
            "            </MetadataSet>\n" +
            "            <MetadataSet containerField='value' name='TacticalConstraints'>\n" +
            "              <MetadataFloat containerField='value' name='maximumAirThreatRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum effective range in miles or kilometers of the longest-range anti-aircraft weapon on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumSurfaceThreatRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum effective range in miles or kilometers of the longest-range anti-surface weapon on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumSubsurfaceThreatRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum effective range in miles or kilometers of the longest-range anti-submarine weapon on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumAirDetectionRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum detection range of the longest-range air detection sensor on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumSurfaceDetectionRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum detection range of the longest-range surface detection sensor on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "              <MetadataFloat containerField='value' name='maximumSubsurfaceDetectionRange' value='0'>\n" +
            "                <MetadataString name='appinfo' value='The maximum detection range of the longest-range subsurface detection sensor on this platform.'/>\n" +
            "              </MetadataFloat>\n" +
            "            </MetadataSet>\n" +
            "          </MetadataSet>\n" +
            "          <MetadataSet containerField='value' name='CurrentConditionParameters'>\n" +
            "            <!-- <MetadataString name=\"appinfo\" value=\"This is a placeholder element which ensures the proper validation of autogenerated SMAL code.\"/> -->\n" +
            "          </MetadataSet>\n" +
            "          <MetadataSet containerField='value' name='NetworkedCommunicationParameterSet'>\n" +
            "            <MetadataSet containerField='value' name='DisConfiguration'>\n" +
            "              <MetadataInteger containerField='value' name='entityKind' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the overall type of this object (for vehicles this value should be 1).'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entityDomain' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the domain of operations of this object (air, surface, sub-surface, etc.).'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entityCountry' value='225'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the country of origin of this object (the value for United States is 225).'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entityCategory' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the type of this vehicle (cruiser or destroyer, tank or truck, bomber or fighter, etc.).'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entitySubCategory' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the class designation of this vehicle (CG-47 Ticonderoga, DDG-51 Arleigh Burke, M1A2, M880, B-52, F-22.'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entitySpecific' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for the specific unit or variant of this object (CG-68, DDG-77, HMMVW w/TOW package).'/>\n" +
            "              </MetadataInteger>\n" +
            "              <MetadataInteger containerField='value' name='entityExtra' value='1'>\n" +
            "                <MetadataString name='appinfo' value='The DIS enumeration for optional equipment or configurations for this vehicle.'/>\n" +
            "              </MetadataInteger>\n" +
            "            </MetadataSet>\n" +
            "          </MetadataSet>\n" +
            "        </MetadataSet>\n" +
            "      </MetadataSet>\n" +
            "    </WorldInfo>\n" +
            "    <!-- ==================== -->\n";
  }

  @SuppressWarnings("unchecked")
  @Override
  /**
   * @return null, no customizer, author can simply edit ProtoInstance
   */
  public Class<? extends BaseCustomizer> getCustomizer()
  {
    return null;
  }

  @Override
  public String getElementName()
  {
    return "SMAL_VehicleMetadataTemplate";
  }
}
