/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.HelpCtx;
import org.openide.util.NbBundle;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;

/**
 * TEXCOORDDAMPER2DCustomizer.java
 * Created on 6 February 2010
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class TEXCOORDDAMPER2DCustomizer extends BaseCustomizer
{
  private TEXCOORDDAMPER2D texCoordDamper2D;
  private JTextComponent target;

  public TEXCOORDDAMPER2DCustomizer(TEXCOORDDAMPER2D texCoordDamper2D, JTextComponent target)
  {
    super(texCoordDamper2D);
    this.texCoordDamper2D = texCoordDamper2D;
    this.target = target;
                   
    HelpCtx.setHelpIDString(this, "TEXCOORDDAMPER2D_ELEM_HELPID");
    
    initComponents();

          tauTF.setText            (texCoordDamper2D.getTau());
    toleranceTF.setText            (texCoordDamper2D.getTolerance());
    orderComboBox.setSelectedIndex (texCoordDamper2D.getOrder());

    initialValueExpandableList.setTitle("initialValue array");
    initialValueExpandableList.setColumnTitles(new String[]{"#","s","t"});
    initialValueExpandableList.setColumnToolTips(new String[]{"index","s horizontal image fraction","t vertical image fraction"});
    initialValueExpandableList.setHeaderTooltip ("initial starting value");
    initialValueExpandableList.doIndexInFirstColumn(true);
    initialValueExpandableList.setFlippableRowData(true);
	initialValueExpandableList.setGeneratePointsPanelVisible(false);

    String[][] saa = texCoordDamper2D.getInitialValue(); // may be 0-length
    initialValueExpandableList.setData(saa);

    initialDestinationExpandableList.setTitle("initialDestination array");
    initialDestinationExpandableList.setColumnTitles(new String[]{"#","s","t"});
    initialDestinationExpandableList.setColumnToolTips(new String[]{"index","s horizontal image fraction","t vertical image fraction"});
    initialDestinationExpandableList.setHeaderTooltip ("initial goal value");
    initialDestinationExpandableList.doIndexInFirstColumn(true);
    initialDestinationExpandableList.setFlippableRowData(true);
	initialDestinationExpandableList.setGeneratePointsPanelVisible(false);

    saa = texCoordDamper2D.getInitialDestination(); // may be 0-length
    initialDestinationExpandableList.setData(saa);
    
        insertCommasCheckBox.setSelected(texCoordDamper2D.isInsertCommas());
    insertLineBreaksCheckBox.setSelected(texCoordDamper2D.isInsertLineBreaks());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1 = getDEFUSEpanel();
        tauLabel = new javax.swing.JLabel();
        tauTF = new javax.swing.JTextField();
        toleranceLabel = new javax.swing.JLabel();
        toleranceTF = new javax.swing.JTextField();
        orderLabel = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        appendLineBreaksCommasPanel = new javax.swing.JPanel();
        appendLabel = new javax.swing.JLabel();
        insertCommasCheckBox = new javax.swing.JCheckBox();
        insertLineBreaksCheckBox = new javax.swing.JCheckBox();
        initialValueExpandableList = new org.web3d.x3d.palette.items.ExpandableList();
        initialDestinationExpandableList = new org.web3d.x3d.palette.items.ExpandableList();
        followerFigureLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        tauLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tauLabel.setText("tau");
        tauLabel.setToolTipText("time constant for filter response in seconds");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 3);
        add(tauLabel, gridBagConstraints);

        tauTF.setToolTipText("time constant for filter response in seconds");
        tauTF.setMinimumSize(new java.awt.Dimension(100, 20));
        tauTF.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(tauTF, gridBagConstraints);

        toleranceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        toleranceLabel.setText("tolerance");
        toleranceLabel.setToolTipText("absolute value for satisfactory completion proximity (-1 lets browser choose)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 3);
        add(toleranceLabel, gridBagConstraints);

        toleranceTF.setToolTipText("absolute value for satisfactory completion proximity (-1 lets browser choose)");
        toleranceTF.setMinimumSize(new java.awt.Dimension(100, 20));
        toleranceTF.setPreferredSize(new java.awt.Dimension(100, 20));
        toleranceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toleranceTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(toleranceTF, gridBagConstraints);

        orderLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orderLabel.setText("order");
        orderLabel.setToolTipText("number of internal filters (larger means smoother response, longer delay)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 3);
        add(orderLabel, gridBagConstraints);

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "0", "1", "2", "3", "4", "5" }));
        orderComboBox.setToolTipText("number of internal filters (larger means smoother response, longer delay)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(orderComboBox, gridBagConstraints);

        appendLineBreaksCommasPanel.setLayout(new java.awt.GridBagLayout());

        appendLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        appendLabel.setText(org.openide.util.NbBundle.getMessage(TEXCOORDDAMPER2DCustomizer.class, "ExpandableList.appendLabel.text")); // NOI18N
        appendLabel.setToolTipText("Append commas or line breaks after each row");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        appendLineBreaksCommasPanel.add(appendLabel, gridBagConstraints);

        insertCommasCheckBox.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        insertCommasCheckBox.setText(org.openide.util.NbBundle.getMessage(TEXCOORDDAMPER2DCustomizer.class, "ExpandableList.insertCommasCheckBox.text")); // NOI18N
        insertCommasCheckBox.setToolTipText(NbBundle.getMessage(getClass(),"ExpandableList.TTIP_COMMAS"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        appendLineBreaksCommasPanel.add(insertCommasCheckBox, gridBagConstraints);

        insertLineBreaksCheckBox.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        insertLineBreaksCheckBox.setText(org.openide.util.NbBundle.getMessage(TEXCOORDDAMPER2DCustomizer.class, "ExpandableList.insertLineBreaksCheckBox.text")); // NOI18N
        insertLineBreaksCheckBox.setToolTipText(NbBundle.getMessage(getClass(),"ExpandableList.TTIP_LINE_BREAKS"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        appendLineBreaksCommasPanel.add(insertLineBreaksCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 20);
        add(appendLineBreaksCommasPanel, gridBagConstraints);

        initialValueExpandableList.setMinimumSize(new java.awt.Dimension(240, 160));
        initialValueExpandableList.setPreferredSize(new java.awt.Dimension(240, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(initialValueExpandableList, gridBagConstraints);

        initialDestinationExpandableList.setMinimumSize(new java.awt.Dimension(240, 160));
        initialDestinationExpandableList.setPreferredSize(new java.awt.Dimension(240, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(initialDestinationExpandableList, gridBagConstraints);

        followerFigureLabel.setBackground(new java.awt.Color(255, 255, 255));
        followerFigureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        followerFigureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/web3d/x3d/palette/items/resources/follower_1.png"))); // NOI18N
        followerFigureLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(followerFigureLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void toleranceTFActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_toleranceTFActionPerformed
    {//GEN-HEADEREND:event_toleranceTFActionPerformed
        checkTolerance ();
    }//GEN-LAST:event_toleranceTFActionPerformed
    private void checkTolerance ()
    {
        SFFloat tolerance = new SFFloat(toleranceTF.getText());
        if ((tolerance.getValue() < 0.0f) && (tolerance.getValue() != -1.0f))
        {
            String message;
            message = "<html><p align='center'>Illegal negative value for <b>tolerance</b>, which must be</p>" +
                       "<p align='center'>0.0 (exact match), positive (absolute value) or -1 (browser choice)</p>" +
                       "<br/><p align='center'>Use positive value for tolerance?</p>";
            NotifyDescriptor descriptor = new NotifyDescriptor.Confirmation(
                    message, "Use positive value for tolerance?", NotifyDescriptor.YES_NO_OPTION);
            if (DialogDisplayer.getDefault().notify(descriptor) == NotifyDescriptor.YES_OPTION)
            {
               toleranceTF.setText(Float.toString(Math.abs(tolerance.getValue())));
            }
        }    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appendLabel;
    private javax.swing.JPanel appendLineBreaksCommasPanel;
    private javax.swing.JLabel followerFigureLabel;
    private org.web3d.x3d.palette.items.ExpandableList initialDestinationExpandableList;
    private org.web3d.x3d.palette.items.ExpandableList initialValueExpandableList;
    private javax.swing.JCheckBox insertCommasCheckBox;
    private javax.swing.JCheckBox insertLineBreaksCheckBox;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel tauLabel;
    private javax.swing.JTextField tauTF;
    private javax.swing.JLabel toleranceLabel;
    private javax.swing.JTextField toleranceTF;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_TEXCOORDDAMPER2D";
  }

  @Override
  public void unloadInput() throws IllegalArgumentException
  {
    unLoadDEFUSE();
    
    checkTolerance ();
    texCoordDamper2D.setTau                (      tauTF.getText().trim());
    texCoordDamper2D.setTolerance          (toleranceTF.getText().trim());
    texCoordDamper2D.setOrder              (orderComboBox.getSelectedItem().toString());
    texCoordDamper2D.setInitialValue       (initialValueExpandableList.getData());
    texCoordDamper2D.setInitialDestination (initialDestinationExpandableList.getData());
    
    texCoordDamper2D.setInsertCommas    (insertCommasCheckBox.isSelected());
    texCoordDamper2D.setInsertLineBreaks(insertLineBreaksCheckBox.isSelected());
    
    // check array sizes
    if ((initialValueExpandableList.getData().length) != (initialDestinationExpandableList.getData().length))
    {
        throw new IllegalArgumentException("Length mismatch, initialValue and destinationValue arrays");
    }    
  }  
}
