/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;

/**
 * VIEWPOINTGROUPCustomizer.java
 * Created on 12 July 2008
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class VIEWPOINTGROUPCustomizer extends BaseCustomizer
{
  private VIEWPOINTGROUP viewpointGroup;
  private JTextComponent target;
  
  /** Creates new form GROUPCustomizer */
  public VIEWPOINTGROUPCustomizer(VIEWPOINTGROUP viewpointGroup, JTextComponent target)
  {
    super(viewpointGroup);
    this.viewpointGroup = viewpointGroup;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "VIEWPOINTGROUP_ELEM_HELPID");
    
    initComponents();
    
    descriptionTA.setText(viewpointGroup.getDescription());
    
    displayedCB.setSelected(viewpointGroup.isDisplayed());
    retainUserOffsetsCB.setSelected(viewpointGroup.isRetainUserOffsets());
    
    center0TF.setText(this.viewpointGroup.getCenter0());
    center1TF.setText(this.viewpointGroup.getCenter1());
    center2TF.setText(this.viewpointGroup.getCenter2());
    
    size0TF.setText(this.viewpointGroup.getSize0());
    size1TF.setText(this.viewpointGroup.getSize1());
    size2TF.setText(this.viewpointGroup.getSize2());
  }
 
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        jPanel1 = new javax.swing.JPanel();
        displayedCB = new javax.swing.JCheckBox();
        retainUserOffsetsCB = new javax.swing.JCheckBox();
        descriptionLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        centerLab = new javax.swing.JLabel();
        center0TF = new javax.swing.JTextField();
        center1TF = new javax.swing.JTextField();
        center2TF = new javax.swing.JTextField();
        sizeLab = new javax.swing.JLabel();
        size0TF = new javax.swing.JTextField();
        size1TF = new javax.swing.JTextField();
        size2TF = new javax.swing.JTextField();
        hintLabel = new javax.swing.JLabel();

        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setLayout(new java.awt.GridBagLayout());

        dEFUSEpanel1.setMaximumSize(null);
        dEFUSEpanel1.setMinimumSize(null);
        dEFUSEpanel1.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        displayedCB.setSelected(true);
        displayedCB.setText("displayed");
        displayedCB.setToolTipText("whether displayed in browser viewpoint list");
        displayedCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        displayedCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(displayedCB, gridBagConstraints);

        retainUserOffsetsCB.setText("retainUserOffsets");
        retainUserOffsetsCB.setToolTipText("whether to return to original location or retain navigated location");
        retainUserOffsetsCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        retainUserOffsetsCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(retainUserOffsetsCB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPanel1, gridBagConstraints);

        descriptionLab.setText("description");
        descriptionLab.setToolTipText("description displayed in viewpoint list");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 3, 3);
        add(descriptionLab, gridBagConstraints);

        descriptionTA.setColumns(1);
        descriptionTA.setLineWrap(true);
        descriptionTA.setRows(3);
        descriptionTA.setToolTipText("description displayed in viewpoint list");
        descriptionTA.setWrapStyleWord(true);
        descriptionTA.setMinimumSize(new java.awt.Dimension(4, 40));
        jScrollPane1.setViewportView(descriptionTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 10);
        add(jScrollPane1, gridBagConstraints);

        centerLab.setText("center");
        centerLab.setToolTipText("center of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 3, 3);
        add(centerLab, gridBagConstraints);

        center0TF.setToolTipText("center x of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(center0TF, gridBagConstraints);

        center1TF.setToolTipText("center y of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(center1TF, gridBagConstraints);

        center2TF.setToolTipText("center z of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 10);
        add(center2TF, gridBagConstraints);

        sizeLab.setText("size");
        sizeLab.setToolTipText("size of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 3, 3);
        add(sizeLab, gridBagConstraints);

        size0TF.setToolTipText("size x of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(size0TF, gridBagConstraints);

        size1TF.setToolTipText("size y of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(size1TF, gridBagConstraints);

        size2TF.setToolTipText("size z of built-in proximity sensor enabling display for this ViewpointGroup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 10);
        add(size2TF, gridBagConstraints);

        hintLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("ViewpointGroup can contain Viewpoint, GeoViewpoint and ViewpointGroup nodes");
        hintLabel.setToolTipText("close this panel to add children nodes");
        hintLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(hintLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField center0TF;
    private javax.swing.JTextField center1TF;
    private javax.swing.JTextField center2TF;
    private javax.swing.JLabel centerLab;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JLabel descriptionLab;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JCheckBox displayedCB;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox retainUserOffsetsCB;
    private javax.swing.JTextField size0TF;
    private javax.swing.JTextField size1TF;
    private javax.swing.JTextField size2TF;
    private javax.swing.JLabel sizeLab;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_VIEWPOINTGROUP";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
    
    viewpointGroup.setCenter0(center0TF.getText().trim());
    viewpointGroup.setCenter1(center1TF.getText().trim());
    viewpointGroup.setCenter2(center2TF.getText().trim());
    viewpointGroup.setDescription(descriptionTA.getText().trim());
    viewpointGroup.setDisplayed(displayedCB.isSelected());
    viewpointGroup.setRetainUserOffsets(retainUserOffsetsCB.isSelected());
    viewpointGroup.setSize0(size0TF.getText().trim());
    viewpointGroup.setSize1(size1TF.getText().trim());
    viewpointGroup.setSize2(size2TF.getText().trim());
  }   
}
