/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;

/**
 * BOUNDARYENHANCEMENTVOLUMESTYLECustomizer.java
 * Created on 15 November 2011
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey and Don Brutzman
 * @version $Id$
 */
public class BOUNDARYENHANCEMENTVOLUMESTYLECustomizer extends BaseCustomizer
{
  private BOUNDARYENHANCEMENTVOLUMESTYLE boundaryEnhancementVolumeStyle;
  private JTextComponent target;
  
  /** Creates new form BOUNDARYENHANCEMENTVOLUMESTYLECustomizer
   * @param boundaryEnhancementVolumeStyle
   * @param target  
   */
  public BOUNDARYENHANCEMENTVOLUMESTYLECustomizer(BOUNDARYENHANCEMENTVOLUMESTYLE boundaryEnhancementVolumeStyle, JTextComponent target)
  {
    super(boundaryEnhancementVolumeStyle);
    this.boundaryEnhancementVolumeStyle = boundaryEnhancementVolumeStyle;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "BOUNDARYENHANCEMENTVOLUMESTYLE_ELEM_HELPID");
    
    initComponents();
    
        enabledCB.setSelected(boundaryEnhancementVolumeStyle.isEnabled());
    boundaryOpacityTF.setText(boundaryEnhancementVolumeStyle.getBoundaryOpacity());
      opacityFactorTF.setText(boundaryEnhancementVolumeStyle.getOpacityFactor());
    retainedOpacityTF.setText(boundaryEnhancementVolumeStyle.getRetainedOpacity());
  }
 
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        enabledLabel = new javax.swing.JLabel();
        enabledCB = new javax.swing.JCheckBox();
        boundaryOpacityLabel = new javax.swing.JLabel();
        boundaryOpacityTF = new javax.swing.JTextField();
        opacityFactorLabel = new javax.swing.JLabel();
        opacityFactorTF = new javax.swing.JTextField();
        retainedOpacityLabel = new javax.swing.JLabel();
        retainedOpacityTF = new javax.swing.JTextField();
        nodeHintPanel = new javax.swing.JPanel();
        hintLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        dEFUSEpanel1.setMinimumSize(new java.awt.Dimension(198, 77));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        enabledLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enabledLabel.setText("enabled");
        enabledLabel.setToolTipText("Enables/disables node operation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledLabel, gridBagConstraints);

        enabledCB.setToolTipText("Enables/disables node operation");
        enabledCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledCB, gridBagConstraints);

        boundaryOpacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        boundaryOpacityLabel.setText("boundaryOpacity");
        boundaryOpacityLabel.setToolTipText("actual-size dimensions of volume data in local coordinate system");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 160, 3, 3);
        add(boundaryOpacityLabel, gridBagConstraints);

        boundaryOpacityTF.setToolTipText("actual-size dimension X value");
        boundaryOpacityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundaryOpacityTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 160);
        add(boundaryOpacityTF, gridBagConstraints);

        opacityFactorLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        opacityFactorLabel.setText("opacityFactor");
        opacityFactorLabel.setToolTipText("position offset from origin of local coordinate system");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 160, 3, 3);
        add(opacityFactorLabel, gridBagConstraints);

        opacityFactorTF.setToolTipText("position offset from origin of local coordinate system");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 160);
        add(opacityFactorTF, gridBagConstraints);

        retainedOpacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        retainedOpacityLabel.setText("retainedOpacity");
        retainedOpacityLabel.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 160, 3, 3);
        add(retainedOpacityLabel, gridBagConstraints);

        retainedOpacityTF.setToolTipText("automatically calculated, can be specified as an optimization or constraint");
        retainedOpacityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retainedOpacityTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 160);
        add(retainedOpacityTF, gridBagConstraints);

        nodeHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nodeHintPanel.setLayout(new java.awt.GridBagLayout());

        hintLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel1.setText("<html><p align='center'><b>BoundaryEnhancementVolumeStyle</b> contains a texture node defining the transferFunction.</p>");
        hintLabel1.setToolTipText("close this panel to add children nodes");
        hintLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        nodeHintPanel.add(hintLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void retainedOpacityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retainedOpacityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retainedOpacityTFActionPerformed

    private void boundaryOpacityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundaryOpacityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundaryOpacityTFActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boundaryOpacityLabel;
    private javax.swing.JTextField boundaryOpacityTF;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JCheckBox enabledCB;
    private javax.swing.JLabel enabledLabel;
    private javax.swing.JLabel hintLabel1;
    private javax.swing.JPanel nodeHintPanel;
    private javax.swing.JLabel opacityFactorLabel;
    private javax.swing.JTextField opacityFactorTF;
    private javax.swing.JLabel retainedOpacityLabel;
    private javax.swing.JTextField retainedOpacityTF;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_BOUNDARYENHANCEMENTVOLUMESTYLE";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
    
    boundaryEnhancementVolumeStyle.setEnabled(enabledCB.isSelected());
    boundaryEnhancementVolumeStyle.setBoundaryOpacity(boundaryOpacityTF.getText().trim());
    boundaryEnhancementVolumeStyle.setOpacityFactor(    opacityFactorTF.getText().trim());
    boundaryEnhancementVolumeStyle.setRetainedOpacity(retainedOpacityTF.getText().trim());
  }   
}
