/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.util.Vector;
import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DSchemaData.*;

/**
 * COLLISIONCOLLECTIONCustomizer.java
 * Created on 27 December 2008
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class COLLISIONCOLLECTIONCustomizer extends BaseCustomizer
{
  private COLLISIONCOLLECTION collisionCollection;
  private JTextComponent target;
  
  /** Creates new form COLLISIONCOLLECTIONCustomizer */
  public COLLISIONCOLLECTIONCustomizer(COLLISIONCOLLECTION collisionCollection, JTextComponent target)
  {
    super(collisionCollection);
    this.collisionCollection = collisionCollection;
    this.target = target;
                             
    HelpCtx.setHelpIDString(this, "COLLISIONCOLLECTION_ELEM_HELPID");   
    
    initComponents();
    
    super.getDEFUSEpanel().setContainerFieldChoices(
            COLLISIONCOLLECTION_ATTR_CONTAINERFIELD_CHOICES, 
            COLLISIONCOLLECTION_ATTR_CONTAINERFIELD_TOOLTIPS);
    // DEFUSEpanel initialization must NOT be repeated or else array of choices will be overwritten

    enabledCB.setSelected(collisionCollection.isEnabled());
    
    bounceTF.setText(collisionCollection.getBounce());
    minBounceSpeedTF.setText(collisionCollection.getMinBounceSpeed());
    softnessConstantForceMixTF.setText(collisionCollection.getSoftnessConstantForceMix());
    softnessErrorCorrectionTF.setText(collisionCollection.getSoftnessErrorCorrection());
    frictionCoefficients0TF.setText(collisionCollection.getFrictionCoefficients0());
    frictionCoefficients1TF.setText(collisionCollection.getFrictionCoefficients1());
    slipFactors0TF.setText(collisionCollection.getSlipFactors0());
    slipFactors1TF.setText(collisionCollection.getSlipFactors1());
    surfaceSpeed0TF.setText(collisionCollection.getSurfaceSpeed0());
    surfaceSpeed1TF.setText(collisionCollection.getSurfaceSpeed1());
    
    // set appliedParameters array
    String[] ta = collisionCollection.getAppliedParameters();  // get selected appliedParameters
    Vector<Integer> v = new Vector<Integer>();
    int wh = 0;
    for(String s : COLLISIONCOLLECTION_ATTR_APPLIEDPARAMETERS_CHOICES) {  // values in list order
      for(String ss : ta) {
        if(ss.equals(s)) {
          v.add(wh);
          break;
        }
      }
      wh++;
    }
    int[] inta = new int[v.size()];
    int count=0;
    for(Integer I : v)
    {
        inta[count++] = I;
    }
    appliedParametersList.setSelectedIndices(inta);
  }
 
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        slipFactorsLabel = new javax.swing.JLabel();
        slipFactors0TF = new javax.swing.JTextField();
        slipFactors1TF = new javax.swing.JTextField();
        frictionCoefficientsLabel = new javax.swing.JLabel();
        frictionCoefficients0TF = new javax.swing.JTextField();
        frictionCoefficients1TF = new javax.swing.JTextField();
        bounceLabel = new javax.swing.JLabel();
        bounceTF = new javax.swing.JTextField();
        surfaceSpeedLabel = new javax.swing.JLabel();
        surfaceSpeed0TF = new javax.swing.JTextField();
        surfaceSpeed1TF = new javax.swing.JTextField();
        enabledLabel = new javax.swing.JLabel();
        enabledCB = new javax.swing.JCheckBox();
        appliedParametersLabel = new javax.swing.JLabel();
        minBounceSpeedLabel = new javax.swing.JLabel();
        minBounceSpeedTF = new javax.swing.JTextField();
        softnessConstantForceMixLabel = new javax.swing.JLabel();
        softnessErrorCorrectionLabel = new javax.swing.JLabel();
        softnessConstantForceMixTF = new javax.swing.JTextField();
        softnessErrorCorrectionTF = new javax.swing.JTextField();
        AppliedParametersScrollPane = new javax.swing.JScrollPane();
        appliedParametersList = new javax.swing.JList<String>();
        nodeHintPanel = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(dEFUSEpanel1, gridBagConstraints);

        slipFactorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        slipFactorsLabel.setText("slipFactors");
        slipFactorsLabel.setToolTipText("slipFactors used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(slipFactorsLabel, gridBagConstraints);

        slipFactors0TF.setColumns(4);
        slipFactors0TF.setToolTipText("slipFactors used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(slipFactors0TF, gridBagConstraints);

        slipFactors1TF.setColumns(4);
        slipFactors1TF.setToolTipText("slipFactors used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 6);
        add(slipFactors1TF, gridBagConstraints);

        frictionCoefficientsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        frictionCoefficientsLabel.setText("frictionCoefficients");
        frictionCoefficientsLabel.setToolTipText("frictionCoefficients used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(frictionCoefficientsLabel, gridBagConstraints);

        frictionCoefficients0TF.setColumns(4);
        frictionCoefficients0TF.setToolTipText("frictionCoefficients used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(frictionCoefficients0TF, gridBagConstraints);

        frictionCoefficients1TF.setColumns(4);
        frictionCoefficients1TF.setToolTipText("frictionCoefficients used for computing surface drag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 6);
        add(frictionCoefficients1TF, gridBagConstraints);

        bounceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bounceLabel.setText("bounce");
        bounceLabel.setToolTipText("bounce indicates bounciness (0 = no bounce at all, 1 = maximum bounce)");
        bounceLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bounceLabel, gridBagConstraints);

        bounceTF.setColumns(4);
        bounceTF.setToolTipText("bounce indicates bounciness (0 = no bounce at all, 1 = maximum bounce)");
        bounceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bounceTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bounceTF, gridBagConstraints);

        surfaceSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        surfaceSpeedLabel.setText("surfaceSpeed");
        surfaceSpeedLabel.setToolTipText("speed vectors for computing surface drag, if contact surfaces move independently of bodies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(surfaceSpeedLabel, gridBagConstraints);

        surfaceSpeed0TF.setColumns(4);
        surfaceSpeed0TF.setToolTipText("speed vectors for computing surface drag, if contact surfaces move independently of bodies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(surfaceSpeed0TF, gridBagConstraints);

        surfaceSpeed1TF.setColumns(4);
        surfaceSpeed1TF.setToolTipText("speed vectors for computing surface drag, if contact surfaces move independently of bodies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 6);
        add(surfaceSpeed1TF, gridBagConstraints);

        enabledLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enabledLabel.setText("enabled");
        enabledLabel.setToolTipText("enable/disable node operation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledLabel, gridBagConstraints);

        enabledCB.setToolTipText("enable/disable node operation");
        enabledCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledCB, gridBagConstraints);

        appliedParametersLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        appliedParametersLabel.setText("appliedParameters");
        appliedParametersLabel.setToolTipText("Global paramaters for collision system");
        appliedParametersLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(appliedParametersLabel, gridBagConstraints);

        minBounceSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minBounceSpeedLabel.setText("minBounceSpeed");
        minBounceSpeedLabel.setToolTipText("minBounceSpeed m/s needed to bounce");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(minBounceSpeedLabel, gridBagConstraints);

        minBounceSpeedTF.setToolTipText("minBounceSpeed m/s needed to bounce");
        minBounceSpeedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBounceSpeedTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(minBounceSpeedTF, gridBagConstraints);

        softnessConstantForceMixLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        softnessConstantForceMixLabel.setText("softnessConstantForceMix");
        softnessConstantForceMixLabel.setToolTipText("applies a constant force value to make colliding surfaces appear to be somewhat soft");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(softnessConstantForceMixLabel, gridBagConstraints);

        softnessErrorCorrectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        softnessErrorCorrectionLabel.setText("softnessErrorCorrection");
        softnessErrorCorrectionLabel.setToolTipText("fraction of collision error fixed in a set of evaluations (0 = no error correction, 1 = all errors corrected in single step)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(softnessErrorCorrectionLabel, gridBagConstraints);

        softnessConstantForceMixTF.setToolTipText("applies a constant force value to make colliding surfaces appear to be somewhat soft");
        softnessConstantForceMixTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softnessConstantForceMixTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(softnessConstantForceMixTF, gridBagConstraints);

        softnessErrorCorrectionTF.setToolTipText("fraction of collision error fixed in a set of evaluations (0 = no error correction, 1 = all errors corrected in single step)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(softnessErrorCorrectionTF, gridBagConstraints);

        appliedParametersList.setListData(COLLISIONCOLLECTION_ATTR_APPLIEDPARAMETERS_CHOICES);
        appliedParametersList.setToolTipText("Global parameters for collision system");
        AppliedParametersScrollPane.setViewportView(appliedParametersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 6);
        add(AppliedParametersScrollPane, gridBagConstraints);

        nodeHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nodeHintPanel.setLayout(new java.awt.GridBagLayout());

        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("<html><p align='center'><b>CollisionCollection</b> holds a collection of objects that can be managed <br /> as a single entity for resolution of inter-object collisions.\n</p>  <br /><p align='center'>Hint: contains a (containerField='collidables') array of <br /> <b>CollisionSpace</b>, <b>CollidableShape</b> or <b>CollidableOffset</b> nodes. </p>");
        hintLabel.setToolTipText("close this panel to add children nodes");
        hintLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        nodeHintPanel.add(hintLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void minBounceSpeedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBounceSpeedTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_minBounceSpeedTFActionPerformed

private void softnessConstantForceMixTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softnessConstantForceMixTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_softnessConstantForceMixTFActionPerformed

    private void bounceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bounceTFActionPerformed
        // TODO test if negative, if so fix.  Repeat for other fields.
    }//GEN-LAST:event_bounceTFActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AppliedParametersScrollPane;
    private javax.swing.JLabel appliedParametersLabel;
    private javax.swing.JList<String> appliedParametersList;
    private javax.swing.JLabel bounceLabel;
    private javax.swing.JTextField bounceTF;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JCheckBox enabledCB;
    private javax.swing.JLabel enabledLabel;
    private javax.swing.JTextField frictionCoefficients0TF;
    private javax.swing.JTextField frictionCoefficients1TF;
    private javax.swing.JLabel frictionCoefficientsLabel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel minBounceSpeedLabel;
    private javax.swing.JTextField minBounceSpeedTF;
    private javax.swing.JPanel nodeHintPanel;
    private javax.swing.JTextField slipFactors0TF;
    private javax.swing.JTextField slipFactors1TF;
    private javax.swing.JLabel slipFactorsLabel;
    private javax.swing.JLabel softnessConstantForceMixLabel;
    private javax.swing.JTextField softnessConstantForceMixTF;
    private javax.swing.JLabel softnessErrorCorrectionLabel;
    private javax.swing.JTextField softnessErrorCorrectionTF;
    private javax.swing.JTextField surfaceSpeed0TF;
    private javax.swing.JTextField surfaceSpeed1TF;
    private javax.swing.JLabel surfaceSpeedLabel;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_COLLISIONCOLLECTION";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
    
    collisionCollection.setEnabled(enabledCB.isSelected());
    
    Object[] oa = appliedParametersList.getSelectedValuesList().toArray();
    String[] sa = new String[oa.length];
    for(int i=0;i<oa.length;i++)
      sa[i] = (String)oa[i];
    collisionCollection.setAppliedParameters(sa);
    
    collisionCollection.setBounce(bounceTF.getText().trim());
    collisionCollection.setMinBounceSpeed(minBounceSpeedTF.getText().trim());
    collisionCollection.setSoftnessConstantForceMix(softnessConstantForceMixTF.getText().trim());
    collisionCollection.setSoftnessErrorCorrection(softnessErrorCorrectionTF.getText().trim());
    collisionCollection.setFrictionCoefficients0(frictionCoefficients0TF.getText().trim());
    collisionCollection.setFrictionCoefficients1(frictionCoefficients1TF.getText().trim());
    collisionCollection.setSlipFactors0(slipFactors0TF.getText().trim());
    collisionCollection.setSlipFactors1(slipFactors1TF.getText().trim());
    collisionCollection.setSurfaceSpeed0(surfaceSpeed0TF.getText().trim());
    collisionCollection.setSurfaceSpeed1(surfaceSpeed1TF.getText().trim());
  }   
}
