/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
Modeling Virtual Environments and Simulation (MOVES) Institute
(http://www.nps.edu and https://MovesInstitute.nps.edu)
nor the names of its contributors may be used to endorse or
promote products derived from this software without specific
prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DSchemaData.*;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;

/**
 * LINEPROPERTIESCustomizer.java
 * Created on July 12, 2007, 3:05 PM
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class LINEPROPERTIESCustomizer extends BaseCustomizer
{

  private LINEPROPERTIES lineproperties;
  private JTextComponent target;

  public LINEPROPERTIESCustomizer(LINEPROPERTIES lineproperties, JTextComponent target)
  {
    super(lineproperties);
    this.lineproperties = lineproperties;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "LINEPROPERTIES_ELEM_HELPID");
    
    initComponents();

    appliedCB.setSelected(lineproperties.isApplied());
    linetypeComboBox.setSelectedIndex(new SFInt32(lineproperties.getLinetype(), 1, null).getValue()-1); // 1-based to 0-based
    lineWidScFactTF.setText(lineproperties.getLinewidthScaleFactor());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jLabel1 = new JLabel();
        appliedCB = new JCheckBox();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        lineWidScFactTF = new JTextField();
        DEFUSEpanel dEFUSEpanel1 = getDEFUSEpanel();
        linetypeComboBox = new JComboBox<String>();
        nodeHintPanel = new JPanel();
        descriptionLabel = new JLabel();

        setLayout(new GridBagLayout());

        jLabel1.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel1.setText("applied");
        jLabel1.setToolTipText("whether or not LineProperties are applied");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 43, 3, 3);
        add(jLabel1, gridBagConstraints);

        appliedCB.setToolTipText("whether or not LineProperties are applied");
        appliedCB.setMargin(new Insets(0, 0, 0, 0));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(appliedCB, gridBagConstraints);

        jLabel2.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel2.setText("linetype");
        jLabel2.setToolTipText("line pattern");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 43, 3, 3);
        add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel3.setText("linewidthScaleFactor");
        jLabel3.setToolTipText("scale for nominal linewidth, zero or less is minimum");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(3, 43, 3, 3);
        add(jLabel3, gridBagConstraints);

        lineWidScFactTF.setToolTipText("scale for nominal linewidth, zero or less is minimum");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(lineWidScFactTF, gridBagConstraints);

        dEFUSEpanel1.setMinimumSize(new Dimension(198, 77));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        linetypeComboBox.setModel(new DefaultComboBoxModel<String>(LINEPROPERTIES_ATTR_LINETYPE_CHOICES));
        linetypeComboBox.setToolTipText("line pattern");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(linetypeComboBox, gridBagConstraints);

        nodeHintPanel.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        nodeHintPanel.setLayout(new GridBagLayout());

        descriptionLabel.setHorizontalAlignment(SwingConstants.CENTER);
        descriptionLabel.setText("<html><b>LineProperties</b> allows fine control over rendering of lines and edges for peer geometry");
        descriptionLabel.setToolTipText("LineProperties affects adjacent geometry nodes");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(10, 3, 10, 3);
        nodeHintPanel.add(descriptionLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox appliedCB;
    private JLabel descriptionLabel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JTextField lineWidScFactTF;
    private JComboBox<String> linetypeComboBox;
    private JPanel nodeHintPanel;
    // End of variables declaration//GEN-END:variables

  // End of variables declaration
  @Override
  public String getNameKey()
  {
    return "NAME_X3D_LINEPROPERTIES";
  }

  @Override
  public void unloadInput()
      throws IllegalArgumentException
  {
    unLoadDEFUSE();

    lineproperties.setApplied(appliedCB.isSelected());
    lineproperties.setLinetype(linetypeComboBox.getSelectedIndex()+1);
    lineproperties.setLinewidthScaleFactor(lineWidScFactTF.getText().trim());
  }
}
