/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;

/**
 * NORMALINTERPOLATORCustomizer.java
 * Created on May 6, 2008
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class NORMALINTERPOLATORCustomizer extends BaseCustomizer
{
  private final NORMALINTERPOLATOR ni;
  private final JTextComponent target;

  private boolean insertCommas, insertLineBreaks = false;
  
  private final int TUPLE_SIZE = 3;
    
  public NORMALINTERPOLATORCustomizer(NORMALINTERPOLATOR ni, JTextComponent target)
  {
    super(ni);
    this.ni = ni;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "NORMALINTERPOLATOR_ELEM_HELPID");
    
    initComponents();
    
    keyTupleTable.setTitle("Normal lists");
    keyTupleTable.setAddColumnButtonTooltip   ("Add column of normal triplets");
    keyTupleTable.setRemoveColumnButtonTooltip("Remove column of normal triplets");
    keyTupleTable.setAddRowButtonTooltip      ("Add row of keyed normal triplets");
    keyTupleTable.setRemoveRowButtonTooltip   ("Remove row of keyed normal triplets");
    keyTupleTable.setColumnsLabelText("columns of normal-vector triplets");
    keyTupleTable.setRowsLabelText   ("rows of keyed normal-vector triplets");
    keyTupleTable.setDefaultTupleValues(new String[]{"0","1","0"}); // 3-tuple
    keyTupleTable.setColumnWidthAndResizeStrategy(true, 50);
    keyTupleTable.setDoNormals(true);

    String[][] saa = ni.getKeysAndValues(); // may be 0-length
    keyTupleTable.setData(TUPLE_SIZE, saa);
    if (saa.length == 0)
    {
        // initialize headers for empty table
        String[][] defaultRow = new String[1][4];
        defaultRow [0] = new String[]{"0","0","1","0"};
        keyTupleTable.setData(TUPLE_SIZE, defaultRow);
        keyTupleTable.setData(TUPLE_SIZE, saa);
    }
    keyTupleTable.setInsertCommas(ni.isInsertCommas());
    keyTupleTable.setInsertLineBreaks(ni.isInsertLineBreaks());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1 = getDEFUSEpanel();
        keyTupleTable = new org.web3d.x3d.palette.items.ExpandableKeyTupleTable();
        normalizeAxisValuesButton = new javax.swing.JButton();
        eventHintPanel = new javax.swing.JPanel();
        eventLabel1 = new javax.swing.JLabel();
        eventLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(keyTupleTable, gridBagConstraints);

        normalizeAxisValuesButton.setText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.normalizeAxisValuesButton.text_1")); // NOI18N
        normalizeAxisValuesButton.setToolTipText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.normalizeAxisValuesButton.toolTipText_1")); // NOI18N
        normalizeAxisValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalizeAxisValuesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 5);
        add(normalizeAxisValuesButton, gridBagConstraints);

        eventHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eventHintPanel.setLayout(new java.awt.GridBagLayout());

        eventLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventLabel1.setText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.eventLabel1.text")); // NOI18N
        eventLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.eventLabel1.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        eventHintPanel.add(eventLabel1, gridBagConstraints);

        eventLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventLabel2.setText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.eventLabel2.text")); // NOI18N
        eventLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(NORMALINTERPOLATORCustomizer.class, "NORMALINTERPOLATORCustomizer.eventLabel2.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        eventHintPanel.add(eventLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 3);
        add(eventHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void normalizeAxisValuesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_normalizeAxisValuesButtonActionPerformed
    {//GEN-HEADEREND:event_normalizeAxisValuesButtonActionPerformed
        String[][] saa = keyTupleTable.getData();
        String[] tuples;
        if      (saa.length == 0) return;
        else
        {
            double normalizationFactor, x, y, z;
            for (int i=0; i < keyTupleTable.getNumberRows(); i++)
            {
                // skip initial key (time fraction) value in position 0
                int columnCount = (keyTupleTable.getNumberColumns() - 1)/3;
                for (int j = 0; j < columnCount; j++)
                {
                    x = new SFDouble(saa[i][j*3 + 1]).getValue();
                    y = new SFDouble(saa[i][j*3 + 2]).getValue();
                    z = new SFDouble(saa[i][j*3 + 3]).getValue();
                    normalizationFactor = Math.sqrt(x * x + y * y + z * z);
                    if (normalizationFactor == 0.0)
                    {
                        NotifyDescriptor descriptor = new NotifyDescriptor.Message(
                                "Found zero-magnitude normal value, reset to 0 1 0", NotifyDescriptor.WARNING_MESSAGE);
                        DialogDisplayer.getDefault().notify(descriptor);
                        saa[i][j*3 + 1] = "0";
                        saa[i][j*3 + 2] = "1";
                        saa[i][j*3 + 3] = "0";
                    }
                    else
                    {
                        saa[i][j*3 + 1] = fiveDigitFormat.format(x / normalizationFactor);
                        saa[i][j*3 + 2] = fiveDigitFormat.format(y / normalizationFactor);
                        saa[i][j*3 + 3] = fiveDigitFormat.format(z / normalizationFactor);
                    }
                }
            }
        }
        keyTupleTable.setData(TUPLE_SIZE, saa);
}//GEN-LAST:event_normalizeAxisValuesButtonActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eventHintPanel;
    private javax.swing.JLabel eventLabel1;
    private javax.swing.JLabel eventLabel2;
    private org.web3d.x3d.palette.items.ExpandableKeyTupleTable keyTupleTable;
    private javax.swing.JButton normalizeAxisValuesButton;
    // End of variables declaration//GEN-END:variables
  @Override
  public String getNameKey()
  {
    return "NAME_X3D_NORMALINTERPOLATOR";
  }

  @Override
  public void unloadInput() throws IllegalArgumentException
  {
    unLoadDEFUSE();
    
    ni.setKeysAndValues(keyTupleTable.getData());

    ni.setInsertCommas    (keyTupleTable.isInsertCommasSet());
    ni.setInsertLineBreaks(keyTupleTable.isInsertLineBreaksSet());
  }  
  
}
