/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.DefaultComboBoxModel;
import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DSchemaData.*;

/**
 * SHADEDVOLUMESTYLECustomizer.java
 * Created on 20 November 2011
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey and Don Brutzman
 * @version $Id$
 */
public class SHADEDVOLUMESTYLECustomizer extends BaseCustomizer
{
  private SHADEDVOLUMESTYLE shadedVolumeStyle;
  private JTextComponent target;
  
  /** Creates new form SHADEDVOLUMESTYLECustomizer
   * @param shadedVolumeStyle
   * @param target  
   */
  public SHADEDVOLUMESTYLECustomizer(SHADEDVOLUMESTYLE shadedVolumeStyle, JTextComponent target)
  {
    super(shadedVolumeStyle);
    this.shadedVolumeStyle = shadedVolumeStyle;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "SHADEDVOLUMESTYLE_ELEM_HELPID");
    
    initComponents();
    
           enabledCB.setSelected(shadedVolumeStyle.isEnabled());
          lightingCB.setSelected(shadedVolumeStyle.isLighting());
           shadowsCB.setSelected(shadedVolumeStyle.isShadows());
   phaseFunctionComboBox.setSelectedItem(shadedVolumeStyle.getPhaseFunction());
  }
 
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        enabledLabel = new javax.swing.JLabel();
        enabledCB = new javax.swing.JCheckBox();
        lightingLabel = new javax.swing.JLabel();
        lightingCB = new javax.swing.JCheckBox();
        shadowsLabel = new javax.swing.JLabel();
        shadowsCB = new javax.swing.JCheckBox();
        phaseFunctionLabel = new javax.swing.JLabel();
        phaseFunctionComboBox = new javax.swing.JComboBox<String>();
        nodeHintPanel = new javax.swing.JPanel();
        hintLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        dEFUSEpanel1.setMinimumSize(new java.awt.Dimension(198, 77));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        enabledLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enabledLabel.setText("enabled");
        enabledLabel.setToolTipText("Enables/disables node operation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 120, 3, 3);
        add(enabledLabel, gridBagConstraints);

        enabledCB.setToolTipText("Enables/disables node operation");
        enabledCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(enabledCB, gridBagConstraints);

        lightingLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lightingLabel.setText("lighting");
        lightingLabel.setToolTipText("Controls whether rendering calculates and applies shading effects to visual output");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 120, 3, 3);
        add(lightingLabel, gridBagConstraints);

        lightingCB.setToolTipText("Controls whether rendering calculates and applies shading effects to visual output");
        lightingCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lightingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightingCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(lightingCB, gridBagConstraints);

        shadowsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shadowsLabel.setText("shadows");
        shadowsLabel.setToolTipText("Whether rendering calculates and applies shadows to visual output (using global illumination model)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 120, 3, 3);
        add(shadowsLabel, gridBagConstraints);

        shadowsCB.setToolTipText("Whether rendering calculates and applies shadows to visual output (using global illumination model)");
        shadowsCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowsCB, gridBagConstraints);

        phaseFunctionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phaseFunctionLabel.setText("phaseFunction");
        phaseFunctionLabel.setToolTipText("define scattering model for implementations using global illumination (NONE or Henyey-Greenstein phase function)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 120, 3, 3);
        add(phaseFunctionLabel, gridBagConstraints);

        phaseFunctionComboBox.setModel(new DefaultComboBoxModel<String>(SHADEDVOLUMESTYLE_ATTR_PHASEFUNCTION_CHOICES));
        phaseFunctionComboBox.setToolTipText("define scattering model for implementations using global illumination (NONE or Henyey-Greenstein phase function)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 120);
        add(phaseFunctionComboBox, gridBagConstraints);

        nodeHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nodeHintPanel.setLayout(new java.awt.GridBagLayout());

        hintLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel1.setText("<html><p align='center'><b>ShadedVolumeStyle</b> can contain a child <b>Material</b> node and a surfaceNormals <i>X3DTexture3DNode</i>.</p>");
        hintLabel1.setToolTipText("multiple style nodes can be applied to volume data");
        hintLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        nodeHintPanel.add(hintLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lightingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightingCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightingCBActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JCheckBox enabledCB;
    private javax.swing.JLabel enabledLabel;
    private javax.swing.JLabel hintLabel1;
    private javax.swing.JCheckBox lightingCB;
    private javax.swing.JLabel lightingLabel;
    private javax.swing.JPanel nodeHintPanel;
    private javax.swing.JComboBox<String> phaseFunctionComboBox;
    private javax.swing.JLabel phaseFunctionLabel;
    private javax.swing.JCheckBox shadowsCB;
    private javax.swing.JLabel shadowsLabel;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_SHADEDVOLUMESTYLE";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
    
    shadedVolumeStyle.setEnabled(enabledCB.isSelected());
    shadedVolumeStyle.setLighting(lightingCB.isSelected());
    shadedVolumeStyle.setShadows(shadowsCB.isSelected());
    shadedVolumeStyle.setPhaseFunction(phaseFunctionComboBox.getSelectedItem().toString().trim());
  }   
}
