/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;

/**
 * TRIANGLESTRIPSETCustomizer.java
 * Created on Sep 13, 2007,10:07 AM
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey and Don Brutzman
 * @version $Id$
 */
public class TRIANGLESTRIPSETCustomizer extends BaseCustomizer
{ 
  private TRIANGLESTRIPSET triangleStripSet;
  private final JTextComponent target;
  
  /** Creates new form TRIANGLESTRIPSETCustomizer */
  public TRIANGLESTRIPSETCustomizer(TRIANGLESTRIPSET triangleStripSet, JTextComponent target)
  {
    super(triangleStripSet);
    this.triangleStripSet = triangleStripSet;
    this.target = target;
                             
    HelpCtx.setHelpIDString(this, "TRIANGLESTRIPSET_ELEM_HELPID");   
    
    initComponents();
    
                ccwCB.setSelected(triangleStripSet.isCcw());
     colorPerVertexCB.setSelected(triangleStripSet.isColorPerVertex());
    normalPerVertexCB.setSelected(triangleStripSet.isNormalPerVertex());
              solidCB.setSelected(triangleStripSet.isSolid());

         stripCountTA.setText(triangleStripSet.getStripCount());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        stripCountLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stripCountTA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ccwLabel = new javax.swing.JLabel();
        ccwCB = new javax.swing.JCheckBox();
        colorPerVertexLabel = new javax.swing.JLabel();
        colorPerVertexCB = new javax.swing.JCheckBox();
        normalPerVertexLabel = new javax.swing.JLabel();
        normalPerVertexCB = new javax.swing.JCheckBox();
        solidLabel = new javax.swing.JLabel();
        solidCB = new javax.swing.JCheckBox();
        nodeHintPanel = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel1, gridBagConstraints);

        stripCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stripCountLabel.setText("stripCount");
        stripCountLabel.setToolTipText("(3..+infinity) stripCount array provides number of vertices in each strip. Warning: do not exceed number of points in contained Coordinate/CoordinateDouble node.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(stripCountLabel, gridBagConstraints);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        stripCountTA.setColumns(20);
        stripCountTA.setLineWrap(true);
        stripCountTA.setRows(3);
        stripCountTA.setToolTipText("(3..+infinity) stripCount array provides number of vertices in each strip. Warning: do not exceed number of points in contained Coordinate/CoordinateDouble node.");
        stripCountTA.setWrapStyleWord(true);
        stripCountTA.setBorder(null);
        stripCountTA.setMinimumSize(new java.awt.Dimension(100, 20));
        jScrollPane2.setViewportView(stripCountTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jScrollPane2, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        ccwLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ccwLabel.setText("ccw");
        ccwLabel.setToolTipText("ccw = counterclockwise: ordering of vertex coordinates orientation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(ccwLabel, gridBagConstraints);

        ccwCB.setToolTipText("ccw = counterclockwise: ordering of vertex coordinates orientation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(ccwCB, gridBagConstraints);

        colorPerVertexLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        colorPerVertexLabel.setText("colorPerVertex");
        colorPerVertexLabel.setToolTipText("whether Color node is applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(colorPerVertexLabel, gridBagConstraints);

        colorPerVertexCB.setToolTipText("whether Color node is applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(colorPerVertexCB, gridBagConstraints);

        normalPerVertexLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        normalPerVertexLabel.setText("normalPerVertex");
        normalPerVertexLabel.setToolTipText("whether Normal vectors are applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(normalPerVertexLabel, gridBagConstraints);

        normalPerVertexCB.setToolTipText("whether Normal vectors are applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(normalPerVertexCB, gridBagConstraints);

        solidLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        solidLabel.setText("solid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(solidLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(solidCB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPanel2, gridBagConstraints);

        nodeHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nodeHintPanel.setLayout(new java.awt.GridBagLayout());

        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("<html><p align='center'><b>TriangleStripSet</b> contains <b>Coordinate|CoordinateDouble</b>,</p> <p align='center'><b>Color|ColorRGBA</b>, <b>Normal</b> and <b>TextureCoordinate|MultiTextureCoordinate</b> nodes</p>");
        hintLabel.setToolTipText("close this panel to add children nodes");
        hintLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        nodeHintPanel.add(hintLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ccwCB;
    private javax.swing.JLabel ccwLabel;
    private javax.swing.JCheckBox colorPerVertexCB;
    private javax.swing.JLabel colorPerVertexLabel;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel nodeHintPanel;
    private javax.swing.JCheckBox normalPerVertexCB;
    private javax.swing.JLabel normalPerVertexLabel;
    private javax.swing.JCheckBox solidCB;
    private javax.swing.JLabel solidLabel;
    private javax.swing.JLabel stripCountLabel;
    private javax.swing.JTextArea stripCountTA;
    // End of variables declaration//GEN-END:variables
  
  
  @Override
  public String getNameKey()
  {
    return "NAME_X3D_TRIANGLESTRIPSET";
  }

  @Override
  public void unloadInput() throws IllegalArgumentException
  {
    unLoadDEFUSE();
    
    triangleStripSet.setCcw(ccwCB.isSelected());
    triangleStripSet.setColorPerVertex(colorPerVertexCB.isSelected());
    triangleStripSet.setNormalPerVertex(normalPerVertexCB.isSelected());
    triangleStripSet.setSolid(solidCB.isSelected());
    
    triangleStripSet.setStripCount(stripCountTA.getText().trim());
  }
}
