/*
Copyright (c) 1995-2021 held by the author(s) .  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (http://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;

/**
 * UNIVERSALJOINTCustomizer.java
 * Created on 3 January 2009
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, Don Brutzman
 * @version $Id$
 */
public class UNIVERSALJOINTCustomizer extends BaseCustomizer
{
  private UNIVERSALJOINT univeralJoint;
  private JTextComponent target;
  
  /** Creates new form UNIVERSALJOINTCustomizer */
  public UNIVERSALJOINTCustomizer(UNIVERSALJOINT univeralJoint, JTextComponent target)
  {
    super(univeralJoint);
    this.univeralJoint = univeralJoint;
    this.target = target;
                              
    HelpCtx.setHelpIDString(this, "UNIVERSALJOINT_ELEM_HELPID");   
    
    initComponents();
    
    String textValue = univeralJoint.getUnformattedForceOutput();
    if (textValue.startsWith("'") && textValue.endsWith("'") && (textValue.length() > 1))
         forceOutputTA.setText(textValue.substring(1, textValue.length()-2));
    else forceOutputTA.setText(textValue);
    
    anchorPointXTF.setText(univeralJoint.getAnchorPointX());
    anchorPointYTF.setText(univeralJoint.getAnchorPointY());
    anchorPointZTF.setText(univeralJoint.getAnchorPointZ());
    
    axis1XTF.setText(univeralJoint.getAxis1X());
    axis1YTF.setText(univeralJoint.getAxis1Y());
    axis1ZTF.setText(univeralJoint.getAxis1Z());
    axis2XTF.setText(univeralJoint.getAxis2X());
    axis2YTF.setText(univeralJoint.getAxis2Y());
    axis2ZTF.setText(univeralJoint.getAxis2Z());
    
    stop1BounceTF.setText(univeralJoint.getStop1Bounce());
    stop2BounceTF.setText(univeralJoint.getStop2Bounce());
    stop1ErrorCorrectionTF.setText(univeralJoint.getStop1ErrorCorrection());
    stop2ErrorCorrectionTF.setText(univeralJoint.getStop2ErrorCorrection());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    GridBagConstraints gridBagConstraints;

    dEFUSEpanel1 = getDEFUSEpanel();
    jLabel1 = new JLabel();
    jScrollPane1 = new JScrollPane();
    forceOutputTA = new JTextArea();
    jLabel3 = new JLabel();
    anchorPointXTF = new JTextField();
    anchorPointYTF = new JTextField();
    anchorPointZTF = new JTextField();
    pan1 = new JPanel();
    jLabel2 = new JLabel();
    axis1XTF = new JTextField();
    axis1YTF = new JTextField();
    axis1ZTF = new JTextField();
    jLabel5 = new JLabel();
    stop1BounceTF = new JTextField();
    stop1ErrorCorrectionTF = new JTextField();
    jLabel6 = new JLabel();
    pan2 = new JPanel();
    axis2Label = new JLabel();
    axis2XTF = new JTextField();
    axis2YTF = new JTextField();
    stop2BounceTF = new JTextField();
    stop2ErrorCorrectionTF = new JTextField();
    axis2ZTF = new JTextField();
    jLabel11 = new JLabel();
    jLabel12 = new JLabel();

    setToolTipText("motor axis vector (0..1)");
    setLayout(new GridBagLayout());
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(dEFUSEpanel1, gridBagConstraints);

    jLabel1.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel1.setText("forceOutput");
    jLabel1.setToolTipText("output fields generated for next frame: ALL, NONE, or exact names of output fields");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(jLabel1, gridBagConstraints);

    jScrollPane1.setToolTipText("output fields generated for next frame: ALL, NONE, or exact names of output fields");

    forceOutputTA.setColumns(20);
    forceOutputTA.setRows(2);
    forceOutputTA.setToolTipText("output fields generated for next frame: ALL, NONE, or exact names of output fields");
    jScrollPane1.setViewportView(forceOutputTA);

    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(jScrollPane1, gridBagConstraints);

    jLabel3.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel3.setText("anchorPoint");
    jLabel3.setToolTipText("anchorPoint is joint center, specified in world coordinates");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(jLabel3, gridBagConstraints);

    anchorPointXTF.setToolTipText("anchorPoint is joint center, specified in world coordinates");
    anchorPointXTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        anchorPointXTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(anchorPointXTF, gridBagConstraints);

    anchorPointYTF.setToolTipText("anchorPoint is joint center, specified in world coordinates");
    anchorPointYTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        anchorPointYTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(anchorPointYTF, gridBagConstraints);

    anchorPointZTF.setToolTipText("anchorPoint is joint center, specified in world coordinates");
    anchorPointZTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        anchorPointZTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(anchorPointZTF, gridBagConstraints);

    pan1.setBorder(BorderFactory.createTitledBorder("1"));
    pan1.setLayout(new GridBagLayout());

    jLabel2.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel2.setText("axis");
    jLabel2.setToolTipText("axis1 defines axis vector of joint connection to body1");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(jLabel2, gridBagConstraints);

    axis1XTF.setColumns(5);
    axis1XTF.setToolTipText("axis1 defines axis vector of joint connection to body1");
    axis1XTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        axis1XTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(axis1XTF, gridBagConstraints);

    axis1YTF.setColumns(5);
    axis1YTF.setToolTipText("axis1 defines axis vector of joint connection to body1");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(axis1YTF, gridBagConstraints);

    axis1ZTF.setColumns(5);
    axis1ZTF.setToolTipText("axis1 defines axis vector of joint connection to body1");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(axis1ZTF, gridBagConstraints);

    jLabel5.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel5.setText("stop1Bounce");
    jLabel5.setToolTipText("velocity factor for bounce back once stop point is reached");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(jLabel5, gridBagConstraints);

    stop1BounceTF.setColumns(5);
    stop1BounceTF.setToolTipText("velocity factor for bounce back once stop point is reached");
    stop1BounceTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        stop1BounceTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(stop1BounceTF, gridBagConstraints);

    stop1ErrorCorrectionTF.setColumns(5);
    stop1ErrorCorrectionTF.setToolTipText("fraction of error correction performed during time step once stop point is reached (0 = no error correction, 1 = all error corrected in single step)");
    stop1ErrorCorrectionTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        stop1ErrorCorrectionTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(stop1ErrorCorrectionTF, gridBagConstraints);

    jLabel6.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel6.setText("stop1ErrorCorrection");
    jLabel6.setToolTipText("fraction of error correction performed during time step once stop point is reached (0 = no error correction, 1 = all error corrected in single step)");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan1.add(jLabel6, gridBagConstraints);

    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(pan1, gridBagConstraints);

    pan2.setBorder(BorderFactory.createTitledBorder("2"));
    pan2.setLayout(new GridBagLayout());

    axis2Label.setHorizontalAlignment(SwingConstants.TRAILING);
    axis2Label.setText("axis");
    axis2Label.setToolTipText("axis2 defines axis vector of joint connection to body2");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(axis2Label, gridBagConstraints);

    axis2XTF.setColumns(5);
    axis2XTF.setToolTipText("axis2 defines axis vector of joint connection to body2");
    axis2XTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        axis2XTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(axis2XTF, gridBagConstraints);

    axis2YTF.setColumns(5);
    axis2YTF.setToolTipText("axis2 defines axis vector of joint connection to body2");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(axis2YTF, gridBagConstraints);

    stop2BounceTF.setColumns(5);
    stop2BounceTF.setToolTipText("velocity factor for bounce back once stop point is reached");
    stop2BounceTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        stop2BounceTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(stop2BounceTF, gridBagConstraints);

    stop2ErrorCorrectionTF.setColumns(5);
    stop2ErrorCorrectionTF.setToolTipText("fraction of error correction performed during time step once stop point is reached (0 = no error correction, 1 = all error corrected in single step)");
    stop2ErrorCorrectionTF.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        stop2ErrorCorrectionTFActionPerformed(evt);
      }
    });
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(stop2ErrorCorrectionTF, gridBagConstraints);

    axis2ZTF.setColumns(5);
    axis2ZTF.setToolTipText("axis2 defines axis vector of joint connection to body2");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.3333;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(axis2ZTF, gridBagConstraints);

    jLabel11.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel11.setText("stop2ErrorCorrection");
    jLabel11.setToolTipText("fraction of error correction performed during time step once stop point is reached (0 = no error correction, 1 = all error corrected in single step)");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(jLabel11, gridBagConstraints);

    jLabel12.setHorizontalAlignment(SwingConstants.TRAILING);
    jLabel12.setText("stop2Bounce");
    jLabel12.setToolTipText("velocity factor for bounce back once stop point is reached");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    pan2.add(jLabel12, gridBagConstraints);

    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(3, 3, 3, 3);
    add(pan2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

private void axis1XTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis1XTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_axis1XTFActionPerformed

private void anchorPointXTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchorPointXTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_anchorPointXTFActionPerformed

private void anchorPointYTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchorPointYTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_anchorPointYTFActionPerformed

private void stop1BounceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop1BounceTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_stop1BounceTFActionPerformed

private void stop1ErrorCorrectionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop1ErrorCorrectionTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_stop1ErrorCorrectionTFActionPerformed

private void axis2XTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis2XTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_axis2XTFActionPerformed

private void anchorPointZTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchorPointZTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_anchorPointZTFActionPerformed

private void stop2BounceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop2BounceTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_stop2BounceTFActionPerformed

private void stop2ErrorCorrectionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop2ErrorCorrectionTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_stop2ErrorCorrectionTFActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JTextField anchorPointXTF;
  private JTextField anchorPointYTF;
  private JTextField anchorPointZTF;
  private JTextField axis1XTF;
  private JTextField axis1YTF;
  private JTextField axis1ZTF;
  private JLabel axis2Label;
  private JTextField axis2XTF;
  private JTextField axis2YTF;
  private JTextField axis2ZTF;
  private DEFUSEpanel dEFUSEpanel1;
  private JTextArea forceOutputTA;
  private JLabel jLabel1;
  private JLabel jLabel11;
  private JLabel jLabel12;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel5;
  private JLabel jLabel6;
  private JScrollPane jScrollPane1;
  private JPanel pan1;
  private JPanel pan2;
  private JTextField stop1BounceTF;
  private JTextField stop1ErrorCorrectionTF;
  private JTextField stop2BounceTF;
  private JTextField stop2ErrorCorrectionTF;
  // End of variables declaration//GEN-END:variables
 
  public String getNameKey()
  {
    return "NAME_X3D_UNIVERSALJOINT";
  }

  public void unloadInput() throws IllegalArgumentException
  {
    univeralJoint.setForceOutput(forceOutputTA.getText().trim());
    
    univeralJoint.setAnchorPointX(anchorPointXTF.getText().trim());
    univeralJoint.setAnchorPointY(anchorPointYTF.getText().trim());
    univeralJoint.setAnchorPointZ(anchorPointZTF.getText().trim());
    
    univeralJoint.setAxis1X(axis1XTF.getText().trim());
    univeralJoint.setAxis1Y(axis1YTF.getText().trim());
    univeralJoint.setAxis1Z(axis1ZTF.getText().trim());
    univeralJoint.setAxis2X(axis2XTF.getText().trim());
    univeralJoint.setAxis2Y(axis2YTF.getText().trim());
    univeralJoint.setAxis2Z(axis2ZTF.getText().trim());
    
    univeralJoint.setStop1Bounce(stop1BounceTF.getText().trim());
    univeralJoint.setStop2Bounce(stop2BounceTF.getText().trim());
    univeralJoint.setStop1ErrorCorrection(stop1ErrorCorrectionTF.getText().trim());   
    univeralJoint.setStop2ErrorCorrection(stop2ErrorCorrectionTF.getText().trim());   
  }
}
