/*
Copyright (c) 1995-2026 held by the author(s).  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (https://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.awt.Color;
import javax.swing.text.JTextComponent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;
/**
 * ENVIRONMENTLIGHTCustomizer.java
 * 
 * @author Don Brutzman
 * @version $Id$
 */
public class ENVIRONMENTLIGHTCustomizer extends BaseCustomizer
{
  private ENVIRONMENTLIGHT environmentLight;
  private JTextComponent target;
  
  /** Creates new form ENVIRONMENTLIGHTCustomizer */
  public ENVIRONMENTLIGHTCustomizer(ENVIRONMENTLIGHT envLight, JTextComponent target)
  {
    super(envLight);
    this.environmentLight = envLight;
    this.target = target;
             
    HelpCtx.setHelpIDString(this, "ENVIRONMENTLIGHT_ELEM_HELPID");
    
    initComponents();
    
    ambientIntensityTF.setText(envLight.getAmbientIntensity());
    color0TF.setText(envLight.getColor0());
    color1TF.setText(envLight.getColor1());
    color2TF.setText(envLight.getColor2());

    bindColorChooserToBetterJTextFields(color0TF,color1TF,color2TF,colorChooser1);
   
    globalCB.setSelected(envLight.isGlobal());
    intensityTF.setText(envLight.getIntensity());
    origin0TF.setText(envLight.getOriginX());
    origin1TF.setText(envLight.getOriginY());
    origin2TF.setText(envLight.getOriginZ());
    
    onCB.setSelected(envLight.isOn());
    rotationTF.setText(envLight.getRotation());
    checkRotation ();
    shadowsCB.setSelected(envLight.isShadows());
    shadowIntensityTF.setText(envLight.getShadowIntensity());
  }

  private void checkRotation ()
  {
//      TODO
//      if ((new SFFloat (rotationTF.getText())).getValue() < 0.0)
//      {
//          String message;
//          message = "<html><center>Negative value provided for <b>radius</b> value, which is illegal.<br/><br/>Convert to default value <b>100</b> meters?";
//          NotifyDescriptor descriptor = new NotifyDescriptor.Confirmation(
//                  message, "radius must be zero or greater", NotifyDescriptor.YES_NO_OPTION);
//          if (DialogDisplayer.getDefault().notify(descriptor) == NotifyDescriptor.YES_OPTION)
//          {
//              rotationTF.setText("100");
//          }
//      }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel1 = getDEFUSEpanel();
        ambientIntensityLabel = new javax.swing.JLabel();
        ambientIntensityTF = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        color0TF = new org.web3d.x3d.palette.BetterJTextField();
        color1TF = new org.web3d.x3d.palette.BetterJTextField();
        color2TF = new org.web3d.x3d.palette.BetterJTextField();
        diffuseCoefficientsLabel = new javax.swing.JLabel();
        intensityLabel = new javax.swing.JLabel();
        intensityTF = new javax.swing.JTextField();
        originLabel = new javax.swing.JLabel();
        origin0TF = new javax.swing.JTextField();
        origin1TF = new javax.swing.JTextField();
        origin2TF = new javax.swing.JTextField();
        globalLabel = new javax.swing.JLabel();
        globalCB = new javax.swing.JCheckBox();
        onLabel = new javax.swing.JLabel();
        onCB = new javax.swing.JCheckBox();
        colorChooser1 = new net.java.dev.colorchooser.ColorChooser();
        rotationLabel = new javax.swing.JLabel();
        rotationTF = new javax.swing.JTextField();
        spacerLabel = new javax.swing.JLabel();
        hintLabel = new javax.swing.JLabel();
        shadowsLabel = new javax.swing.JLabel();
        shadowsCB = new javax.swing.JCheckBox();
        shadowIntensityLabel = new javax.swing.JLabel();
        shadowIntensityTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(620, 420));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(dEFUSEpanel1, gridBagConstraints);

        ambientIntensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ambientIntensityLabel.setText("ambientIntensity");
        ambientIntensityLabel.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(ambientIntensityLabel, gridBagConstraints);

        ambientIntensityTF.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
        ambientIntensityTF.setMinimumSize(new java.awt.Dimension(60, 22));
        ambientIntensityTF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(ambientIntensityTF, gridBagConstraints);

        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        colorLabel.setText("color");
        colorLabel.setToolTipText("color of light, applied to colors of objects");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(colorLabel, gridBagConstraints);

        color0TF.setToolTipText("color of light, applied to colors of objects");
        color0TF.setMinimumSize(new java.awt.Dimension(60, 22));
        color0TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color0TF, gridBagConstraints);

        color1TF.setToolTipText("color of light, applied to colors of objects");
        color1TF.setMinimumSize(new java.awt.Dimension(60, 22));
        color1TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color1TF, gridBagConstraints);

        color2TF.setToolTipText("color of light, applied to colors of objects");
        color2TF.setMinimumSize(new java.awt.Dimension(60, 22));
        color2TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color2TF, gridBagConstraints);

        diffuseCoefficientsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        diffuseCoefficientsLabel.setText("diffuseCoefficients");
        diffuseCoefficientsLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(diffuseCoefficientsLabel, gridBagConstraints);

        intensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        intensityLabel.setText("intensity");
        intensityLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(intensityLabel, gridBagConstraints);

        intensityTF.setToolTipText("[0,1] brightness of direct light");
        intensityTF.setMinimumSize(new java.awt.Dimension(60, 22));
        intensityTF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(intensityTF, gridBagConstraints);

        originLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        originLabel.setText("origin");
        originLabel.setToolTipText("position of light relative to local coordinate system");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(originLabel, gridBagConstraints);

        origin0TF.setToolTipText("position of light relative to local coordinate system");
        origin0TF.setMinimumSize(new java.awt.Dimension(60, 22));
        origin0TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(origin0TF, gridBagConstraints);

        origin1TF.setToolTipText("position of light relative to local coordinate system");
        origin1TF.setMinimumSize(new java.awt.Dimension(60, 22));
        origin1TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(origin1TF, gridBagConstraints);

        origin2TF.setToolTipText("position of light relative to local coordinate system");
        origin2TF.setMinimumSize(new java.awt.Dimension(60, 22));
        origin2TF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(origin2TF, gridBagConstraints);

        globalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        globalLabel.setText("global");
        globalLabel.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(globalLabel, gridBagConstraints);

        globalCB.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
        globalCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        globalCB.setMinimumSize(new java.awt.Dimension(60, 22));
        globalCB.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(globalCB, gridBagConstraints);

        onLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        onLabel.setText("on");
        onLabel.setToolTipText("enables/disables this light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(onLabel, gridBagConstraints);

        onCB.setToolTipText("enables/disables this light");
        onCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        onCB.setMinimumSize(new java.awt.Dimension(60, 22));
        onCB.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(onCB, gridBagConstraints);

        colorChooser1.setMaximumSize(new java.awt.Dimension(22, 22));
        colorChooser1.setMinimumSize(new java.awt.Dimension(22, 22));
        colorChooser1.setPreferredSize(new java.awt.Dimension(22, 22));
        colorChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorChooser1Layout = new javax.swing.GroupLayout(colorChooser1);
        colorChooser1.setLayout(colorChooser1Layout);
        colorChooser1Layout.setHorizontalGroup(
            colorChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        colorChooser1Layout.setVerticalGroup(
            colorChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(colorChooser1, gridBagConstraints);

        rotationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rotationLabel.setText("rotation");
        rotationLabel.setToolTipText("maximum effective distance of light relative to local light position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(rotationLabel, gridBagConstraints);

        rotationTF.setToolTipText("maximum effective distance of light relative to local light position");
        rotationTF.setMinimumSize(new java.awt.Dimension(60, 22));
        rotationTF.setPreferredSize(new java.awt.Dimension(60, 22));
        rotationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotationTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(rotationTF, gridBagConstraints);

        spacerLabel.setText("        ");
        spacerLabel.setMaximumSize(null);
        spacerLabel.setMinimumSize(new java.awt.Dimension(10, 16));
        spacerLabel.setPreferredSize(new java.awt.Dimension(10, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(spacerLabel, gridBagConstraints);

        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("<html><p align=\"center\"><b>EnvironmentLight</b> supports Image Based Lighting (IBL) techniques by specifying <br />\nlight-source intensity around a given location (i.e., the environment) as a cube map. </p>\n<br />\n<p align=\"center\">\nContained ambientIntensity and specularTexture nodes (ComposedCubeMapTexture, GeneratedCubeMapTexture, ImageCubeMapTexture) define radiance maps <br />\nLighting illuminates all geometry except lines and points.</p>\n<br />\n<p align=\"center\">  Lights have no visible shape themselves and lighting effects continue through any intermediate geometry.</p>");
        hintLabel.setToolTipText(org.openide.util.NbBundle.getMessage(ENVIRONMENTLIGHTCustomizer.class, "INTEGERSEQUENCERCustomizer.eventLabel3.toolTipText")); // NOI18N
        hintLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(hintLabel, gridBagConstraints);

        shadowsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shadowsLabel.setText("shadows");
        shadowsLabel.setToolTipText("whether shadows result from this light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowsLabel, gridBagConstraints);

        shadowsCB.setToolTipText("whether shadows result from this light");
        shadowsCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shadowsCB.setMinimumSize(new java.awt.Dimension(60, 22));
        shadowsCB.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowsCB, gridBagConstraints);

        shadowIntensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shadowIntensityLabel.setText("shadowIntensity");
        shadowIntensityLabel.setToolTipText("[0,1] darkness of shadows from this light (0 is no shadow, 1 is full-intensity shadow)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowIntensityLabel, gridBagConstraints);

        shadowIntensityTF.setToolTipText("[0,1] darkness of shadows from this light (0 is no shadow, 1 is full-intensity shadow)");
        shadowIntensityTF.setMinimumSize(new java.awt.Dimension(60, 22));
        shadowIntensityTF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowIntensityTF, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

  private void colorChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooser1ActionPerformed
    Color c = colorChooser1.getColor();
    color0TF.setText(colorFormat.format(c.getRed()  /255.0f));
    color1TF.setText(colorFormat.format(c.getGreen()/255.0f));
    color2TF.setText(colorFormat.format(c.getBlue() /255.0f));
  }//GEN-LAST:event_colorChooser1ActionPerformed

  private void rotationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotationTFActionPerformed
      checkRotation ();
  }//GEN-LAST:event_rotationTFActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ambientIntensityLabel;
    private javax.swing.JTextField ambientIntensityTF;
    private org.web3d.x3d.palette.BetterJTextField color0TF;
    private org.web3d.x3d.palette.BetterJTextField color1TF;
    private org.web3d.x3d.palette.BetterJTextField color2TF;
    private net.java.dev.colorchooser.ColorChooser colorChooser1;
    private javax.swing.JLabel colorLabel;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel1;
    private javax.swing.JLabel diffuseCoefficientsLabel;
    private javax.swing.JCheckBox globalCB;
    private javax.swing.JLabel globalLabel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel intensityLabel;
    private javax.swing.JTextField intensityTF;
    private javax.swing.JCheckBox onCB;
    private javax.swing.JLabel onLabel;
    private javax.swing.JTextField origin0TF;
    private javax.swing.JTextField origin1TF;
    private javax.swing.JTextField origin2TF;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel rotationLabel;
    private javax.swing.JTextField rotationTF;
    private javax.swing.JLabel shadowIntensityLabel;
    private javax.swing.JTextField shadowIntensityTF;
    private javax.swing.JCheckBox shadowsCB;
    private javax.swing.JLabel shadowsLabel;
    private javax.swing.JLabel spacerLabel;
    // End of variables declaration//GEN-END:variables

  @Override
  public String getNameKey()
  {
    return "NAME_X3D_ENVIRONMENTLIGHT";
  }

  @Override
  public void unloadInput()
  {
    unLoadDEFUSE();
     
    environmentLight.setAmbientIntensity(ambientIntensityTF.getText().trim());
    
    environmentLight.setColor0(color0TF.getText().trim());
    environmentLight.setColor1(color1TF.getText().trim());
    environmentLight.setColor2(color2TF.getText().trim());
    
    environmentLight.setGlobal(globalCB.isSelected());
    
    environmentLight.setIntensity(intensityTF.getText().trim());
    environmentLight.setOn(onCB.isSelected());
    environmentLight.setOriginX(origin0TF.getText().trim());
    environmentLight.setOriginY(origin1TF.getText().trim());
    environmentLight.setOriginZ(origin2TF.getText().trim());
    
    checkRotation ();
    environmentLight.setRotation(rotationTF.getText().trim());
    
    environmentLight.setShadows(shadowsCB.isSelected());
    environmentLight.setShadowIntensity(shadowIntensityTF.getText().trim());
  }
  
}
