/*
Copyright (c) 1995-2026 held by the author(s).  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (https://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import javax.swing.text.JTextComponent;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DSchemaData.INDEXEDQUADSET_CONTAINERFIELD_CHOICES;
import static org.web3d.x3d.types.X3DSchemaData.INDEXEDQUADSET_CONTAINERFIELD_TOOLTIPS;

/**
 * INDEXEDQUADSETCustomizer.java
 * Created on Sep 13, 2007,10:07 AM
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey
 * @version $Id$
 */
public class INDEXEDQUADSETCustomizer extends BaseCustomizer
{ 
  private final INDEXEDQUADSET indexedQuadSet;
  private final JTextComponent target;
  
  /** Creates new form INDEXEDQUADSETCustomizer
   * @param iqs
   * @param target Swing component of interest 
   */
  public INDEXEDQUADSETCustomizer(INDEXEDQUADSET iqs, JTextComponent target)
  {
    super(iqs);
    this.indexedQuadSet = iqs;
    this.target = target;
                             
    HelpCtx.setHelpIDString(this, "INDEXEDQUADSET_ELEM_HELPID");   
    
    initComponents();
    
    super.getDEFUSEpanel().setContainerFieldChoices(INDEXEDQUADSET_CONTAINERFIELD_CHOICES, INDEXEDQUADSET_CONTAINERFIELD_TOOLTIPS);
    super.getDEFUSEpanel().setContainerField(indexedQuadSet.getContainerField()); // reset value to match updated JComboBox data model
    // DEFUSEpanel initialization must NOT be repeated or else array of choices will be overwritten

    ccwCB.setSelected(indexedQuadSet.isCcw());
    colorPerVertexCB.setSelected(indexedQuadSet.isColorPerVertex());
    normalPerVertexCB.setSelected(indexedQuadSet.isNormalPerVertex());
    solidCB.setSelected(indexedQuadSet.isSolid());

    indexTA.setText(indexedQuadSet.getIndex());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel = getDEFUSEpanel();
        indexLabel = new javax.swing.JLabel();
        indexScrollPane = new javax.swing.JScrollPane();
        indexTA = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        ccwLabel = new javax.swing.JLabel();
        ccwCB = new javax.swing.JCheckBox();
        colorPerVertexLabel = new javax.swing.JLabel();
        colorPerVertexCB = new javax.swing.JCheckBox();
        normalPerVertexLabel = new javax.swing.JLabel();
        normalPerVertexCB = new javax.swing.JCheckBox();
        solidLabel = new javax.swing.JLabel();
        solidCB = new javax.swing.JCheckBox();
        nodeHintPanel = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(606, 270));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel, gridBagConstraints);

        indexLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        indexLabel.setText("index");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 14, 3, 3);
        add(indexLabel, gridBagConstraints);

        indexScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        indexScrollPane.setMinimumSize(new java.awt.Dimension(80, 40));

        indexTA.setColumns(20);
        indexTA.setLineWrap(true);
        indexTA.setRows(4);
        indexTA.setToolTipText("index specifies triangles by connecting Coordinate vertices, each individual fan separated by -1 sentinel value");
        indexTA.setWrapStyleWord(true);
        indexTA.setBorder(null);
        indexTA.setMinimumSize(new java.awt.Dimension(100, 20));
        indexScrollPane.setViewportView(indexTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(indexScrollPane, gridBagConstraints);

        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        ccwLabel.setText("ccw");
        ccwLabel.setToolTipText("ccw = counterclockwise: ordering of vertex coordinates orientation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        buttonPanel.add(ccwLabel, gridBagConstraints);

        ccwCB.setToolTipText("ccw = counterclockwise: ordering of vertex coordinates orientation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        buttonPanel.add(ccwCB, gridBagConstraints);

        colorPerVertexLabel.setText("colorPerVertex");
        colorPerVertexLabel.setToolTipText("whether Color node is applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        buttonPanel.add(colorPerVertexLabel, gridBagConstraints);

        colorPerVertexCB.setToolTipText("whether Color node is applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        buttonPanel.add(colorPerVertexCB, gridBagConstraints);

        normalPerVertexLabel.setText("normalPerVertex");
        normalPerVertexLabel.setToolTipText("whether Normal vectors are applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        buttonPanel.add(normalPerVertexLabel, gridBagConstraints);

        normalPerVertexCB.setToolTipText("whether Normal vectors are applied per vertex (true) or per polygon (false)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        buttonPanel.add(normalPerVertexCB, gridBagConstraints);

        solidLabel.setText("solid");
        solidLabel.setToolTipText("Setting solid true means draw only one side of polygons (backface culling on), setting solid false means draw both sides of polygons (backface culling off)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        buttonPanel.add(solidLabel, gridBagConstraints);

        solidCB.setToolTipText("Setting solid true means draw only one side of polygons (backface culling on), setting solid false means draw both sides of polygons (backface culling off)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        buttonPanel.add(solidCB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(buttonPanel, gridBagConstraints);

        nodeHintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nodeHintPanel.setLayout(new java.awt.GridBagLayout());

        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("<html><p align='center'><b>IndexedQuadSet</b> contains <b>Coordinate|CoordinateDouble</b>,</p> <p align='center'><b>Color|ColorRGBA</b>, <b>Normal</b> and <b>TextureCoordinate|MultiTextureCoordinate</b> nodes</p>");
        hintLabel.setToolTipText("close this panel to add children nodes");
        hintLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        nodeHintPanel.add(hintLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nodeHintPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox ccwCB;
    private javax.swing.JLabel ccwLabel;
    private javax.swing.JCheckBox colorPerVertexCB;
    private javax.swing.JLabel colorPerVertexLabel;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JScrollPane indexScrollPane;
    private javax.swing.JTextArea indexTA;
    private javax.swing.JPanel nodeHintPanel;
    private javax.swing.JCheckBox normalPerVertexCB;
    private javax.swing.JLabel normalPerVertexLabel;
    private javax.swing.JCheckBox solidCB;
    private javax.swing.JLabel solidLabel;
    // End of variables declaration//GEN-END:variables
  
  
  @Override
  public String getNameKey()
  {
    return "NAME_X3D_INDEXEDQUADSET";
  }

  @Override
  public void unloadInput() throws IllegalArgumentException
  {
    unLoadDEFUSE();
    
    indexedQuadSet.setCcw(ccwCB.isSelected());
    indexedQuadSet.setColorPerVertex(colorPerVertexCB.isSelected());
    indexedQuadSet.setNormalPerVertex(normalPerVertexCB.isSelected());
    indexedQuadSet.setSolid(solidCB.isSelected());
    
    indexedQuadSet.setIndex(indexTA.getText().trim());
  }
  // TODO checkIndices(), no -1 sentinels allowed; change indexTA to expandableList
}
