/*
Copyright (c) 1995-2026 held by the author(s).  All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the
      distribution.
 * Neither the names of the Naval Postgraduate School (NPS)
      Modeling Virtual Environments and Simulation (MOVES) Institute
      (https://www.nps.edu and https://MovesInstitute.nps.edu)
      nor the names of its contributors may be used to endorse or
      promote products derived from this software without specific
      prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
 */

package org.web3d.x3d.palette.items;

import java.awt.Color;
import javax.swing.text.JTextComponent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.HelpCtx;
import static org.web3d.x3d.types.X3DPrimitiveTypes.*;

/**
 * TEXTUREPROJECTORCustomizer.java
 * 
 * @author Don Brutzman
 * @version $Id$
 */
public class TEXTUREPROJECTORCustomizer extends BaseCustomizer
{
  private TEXTUREPROJECTOR textureProjector;
  private JTextComponent target;
  
  /** Creates new form TEXTUREPROJECTORCustomizer */
  public TEXTUREPROJECTORCustomizer(TEXTUREPROJECTOR textureProjector, JTextComponent target)
  {
    super(textureProjector);
    this.textureProjector = textureProjector;
    this.target = target;
    
    HelpCtx.setHelpIDString(this, "TEXTUREPROJECTOR_ELEM_HELPID");
    
    initComponents();
    
    ambientIntensityTF.setText(textureProjector.getAmbientIntensity());
    
    color0TF.setText(textureProjector.getColor0());
    color1TF.setText(textureProjector.getColor1());
    color2TF.setText(textureProjector.getColor2());

    bindColorChooserToBetterJTextFields(color0TF,color1TF,color2TF,colorChooser);

    globalCB.setSelected(textureProjector.isGlobal());
    intensityTF.setText(textureProjector.getIntensity());
    
    descriptionTextField.setText(textureProjector.getDescription());
    directionXTF.setText(textureProjector.getDirectionX());
    directionYTF.setText(textureProjector.getDirectionY());
    directionZTF.setText(textureProjector.getDirectionZ());
    if (directionXTF.getText().equals("0") && directionYTF.getText().equals("0") && directionZTF.getText().equals("0")) normalizeButton.doClick();
    
    onCB.setSelected(textureProjector.isOn());
    
    shadowsCB.setSelected(textureProjector.isShadows());
    shadowIntensityTF.setText(textureProjector.getShadowIntensity());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dEFUSEpanel = getDEFUSEpanel();
        ambientLabel = new javax.swing.JLabel();
        ambientIntensityTF = new javax.swing.JTextField();
        rLabel = new javax.swing.JLabel();
        gLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        color0TF = new org.web3d.x3d.palette.BetterJTextField();
        color1TF = new org.web3d.x3d.palette.BetterJTextField();
        color2TF = new org.web3d.x3d.palette.BetterJTextField();
        colorChooser = new net.java.dev.colorchooser.ColorChooser();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        directionLabel = new javax.swing.JLabel();
        directionYTF = new javax.swing.JTextField();
        directionZTF = new javax.swing.JTextField();
        directionXTF = new javax.swing.JTextField();
        intensityLabel = new javax.swing.JLabel();
        intensityTF = new javax.swing.JTextField();
        onLabel = new javax.swing.JLabel();
        onCB = new javax.swing.JCheckBox();
        globalLabel = new javax.swing.JLabel();
        globalCB = new javax.swing.JCheckBox();
        normalizeButton = new javax.swing.JButton();
        shadowsLabel = new javax.swing.JLabel();
        shadowsCB = new javax.swing.JCheckBox();
        shadowIntensityLabel = new javax.swing.JLabel();
        shadowIntensityTF = new javax.swing.JTextField();
        hintPanel = new javax.swing.JPanel();
        eventsLabel = new javax.swing.JLabel();
        nearDistanceLabel = new javax.swing.JLabel();
        nearDistanceTF = new javax.swing.JTextField();
        farDistanceLabel = new javax.swing.JLabel();
        farDistanceTF = new javax.swing.JTextField();
        fieldOfViewLabel = new javax.swing.JLabel();
        fieldOfViewTF = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(650, 480));
        setPreferredSize(new java.awt.Dimension(650, 480));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(dEFUSEpanel, gridBagConstraints);

        ambientLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ambientLabel.setText("ambientIntensity");
        ambientLabel.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(ambientLabel, gridBagConstraints);

        ambientIntensityTF.setToolTipText("[0,1] brightness of ambient (nondirectional background) light");
        ambientIntensityTF.setMaximumSize(null);
        ambientIntensityTF.setMinimumSize(new java.awt.Dimension(40, 20));
        ambientIntensityTF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(ambientIntensityTF, gridBagConstraints);

        rLabel.setText("r");
        rLabel.setToolTipText("red component [0..1]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(rLabel, gridBagConstraints);

        gLabel.setText("g");
        gLabel.setToolTipText("green component [0..1]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(gLabel, gridBagConstraints);

        bLabel.setText("b");
        bLabel.setToolTipText("blue component [0..1]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        add(bLabel, gridBagConstraints);

        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        colorLabel.setText("color");
        colorLabel.setToolTipText("color of light, applied to colors of objects");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(colorLabel, gridBagConstraints);

        color0TF.setToolTipText("color of light, applied to colors of objects");
        color0TF.setMaximumSize(null);
        color0TF.setMinimumSize(new java.awt.Dimension(40, 20));
        color0TF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color0TF, gridBagConstraints);

        color1TF.setToolTipText("color of light, applied to colors of objects");
        color1TF.setMaximumSize(null);
        color1TF.setMinimumSize(new java.awt.Dimension(40, 20));
        color1TF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color1TF, gridBagConstraints);

        color2TF.setToolTipText("color of light, applied to colors of objects");
        color2TF.setMaximumSize(null);
        color2TF.setMinimumSize(new java.awt.Dimension(40, 20));
        color2TF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(color2TF, gridBagConstraints);

        colorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorChooserLayout = new javax.swing.GroupLayout(colorChooser);
        colorChooser.setLayout(colorChooserLayout);
        colorChooserLayout.setHorizontalGroup(
            colorChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        colorChooserLayout.setVerticalGroup(
            colorChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(colorChooser, gridBagConstraints);

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        descriptionLabel.setText("description");
        descriptionLabel.setToolTipText("Text description or navigation hint identifying this Viewpoint. Hint: use spaces, make descriptions clear and readable. ");
        descriptionLabel.setMaximumSize(new java.awt.Dimension(200, 22));
        descriptionLabel.setMinimumSize(new java.awt.Dimension(130, 22));
        descriptionLabel.setOpaque(true);
        descriptionLabel.setPreferredSize(new java.awt.Dimension(130, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(descriptionLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(descriptionTextField, gridBagConstraints);

        directionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        directionLabel.setText("direction");
        directionLabel.setToolTipText("direction vector of light axis relative to local coordinate system");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(directionLabel, gridBagConstraints);

        directionYTF.setToolTipText("y direction vector of light axis relative to local coordinate system");
        directionYTF.setMaximumSize(null);
        directionYTF.setMinimumSize(new java.awt.Dimension(40, 20));
        directionYTF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(directionYTF, gridBagConstraints);

        directionZTF.setToolTipText("z direction vector of light axis relative to local coordinate system");
        directionZTF.setMaximumSize(null);
        directionZTF.setMinimumSize(new java.awt.Dimension(40, 20));
        directionZTF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(directionZTF, gridBagConstraints);

        directionXTF.setToolTipText("x direction vector of light axis relative to local coordinate system");
        directionXTF.setMaximumSize(null);
        directionXTF.setMinimumSize(new java.awt.Dimension(40, 20));
        directionXTF.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(directionXTF, gridBagConstraints);

        intensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        intensityLabel.setText("intensity");
        intensityLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(intensityLabel, gridBagConstraints);

        intensityTF.setToolTipText("[0,1] brightness of direct light");
        intensityTF.setMaximumSize(null);
        intensityTF.setMinimumSize(new java.awt.Dimension(40, 20));
        intensityTF.setPreferredSize(new java.awt.Dimension(40, 20));
        intensityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensityTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(intensityTF, gridBagConstraints);

        onLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        onLabel.setText("on");
        onLabel.setToolTipText("enables/disables this light source");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(onLabel, gridBagConstraints);

        onCB.setToolTipText("enables/disables this light source");
        onCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        onCB.setMaximumSize(null);
        onCB.setMinimumSize(new java.awt.Dimension(40, 20));
        onCB.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(onCB, gridBagConstraints);

        globalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        globalLabel.setText("global");
        globalLabel.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(globalLabel, gridBagConstraints);

        globalCB.setToolTipText("global lights illuminate all objects, scoped lights only affect local transformation hierarchy");
        globalCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        globalCB.setMaximumSize(null);
        globalCB.setMinimumSize(new java.awt.Dimension(40, 20));
        globalCB.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(globalCB, gridBagConstraints);

        normalizeButton.setText("normalize");
        normalizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalizeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(normalizeButton, gridBagConstraints);

        shadowsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shadowsLabel.setText("shadows");
        shadowsLabel.setToolTipText("whether shadows result from this light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowsLabel, gridBagConstraints);

        shadowsCB.setToolTipText("whether shadows result from this light");
        shadowsCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shadowsCB.setMinimumSize(new java.awt.Dimension(60, 22));
        shadowsCB.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowsCB, gridBagConstraints);

        shadowIntensityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shadowIntensityLabel.setText("shadowIntensity");
        shadowIntensityLabel.setToolTipText("[0,1] darkness of shadows from this light (0 is no shadow, 1 is full-intensity shadow)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowIntensityLabel, gridBagConstraints);

        shadowIntensityTF.setToolTipText("[0,1] darkness of shadows from this light (0 is no shadow, 1 is full-intensity shadow)");
        shadowIntensityTF.setMinimumSize(new java.awt.Dimension(60, 22));
        shadowIntensityTF.setPreferredSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(shadowIntensityTF, gridBagConstraints);

        hintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hintPanel.setLayout(new java.awt.GridBagLayout());

        eventsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventsLabel.setText("<html> <p align=\"center\"><b>TextureProjector</b>s a perspective-based light that projects a texture into the scene, \n<br />\napplying the projected texture to any geometry that intersects the perspective projection volume.</p>\n<br />\n<p align='center'><i>aspectRatio</i> is an output event when the contained <b>ImageTexture</b> is loaded.</p>");
        eventsLabel.setToolTipText("Create a ROUTE to connect output events");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        hintPanel.add(eventsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 3);
        add(hintPanel, gridBagConstraints);

        nearDistanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nearDistanceLabel.setText("nearDistance");
        nearDistanceLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nearDistanceLabel, gridBagConstraints);

        nearDistanceTF.setToolTipText("[0,1] brightness of direct light");
        nearDistanceTF.setMaximumSize(null);
        nearDistanceTF.setMinimumSize(new java.awt.Dimension(40, 20));
        nearDistanceTF.setPreferredSize(new java.awt.Dimension(40, 20));
        nearDistanceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearDistanceTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(nearDistanceTF, gridBagConstraints);

        farDistanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        farDistanceLabel.setText("farDistance");
        farDistanceLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(farDistanceLabel, gridBagConstraints);

        farDistanceTF.setToolTipText("[0,1] brightness of direct light");
        farDistanceTF.setMaximumSize(null);
        farDistanceTF.setMinimumSize(new java.awt.Dimension(40, 20));
        farDistanceTF.setPreferredSize(new java.awt.Dimension(40, 20));
        farDistanceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farDistanceTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(farDistanceTF, gridBagConstraints);

        fieldOfViewLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fieldOfViewLabel.setText("fieldOfView");
        fieldOfViewLabel.setToolTipText("[0,1] brightness of direct light");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(fieldOfViewLabel, gridBagConstraints);

        fieldOfViewTF.setToolTipText("[0,1] brightness of direct light");
        fieldOfViewTF.setMaximumSize(null);
        fieldOfViewTF.setMinimumSize(new java.awt.Dimension(40, 20));
        fieldOfViewTF.setPreferredSize(new java.awt.Dimension(40, 20));
        fieldOfViewTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfViewTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(fieldOfViewTF, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
                                        

  private void intensityTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_intensityTFActionPerformed
  {//GEN-HEADEREND:event_intensityTFActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_intensityTFActionPerformed

  private void normalizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalizeButtonActionPerformed
        double normalizationFactor, x, y, z;

        x     = new SFDouble(directionXTF.getText()).getValue();
        y     = new SFDouble(directionYTF.getText()).getValue();
        z     = new SFDouble(directionZTF.getText()).getValue();

        normalizationFactor = Math.sqrt(x * x + y * y + z * z);
        if (normalizationFactor == 0.0)
        {
            NotifyDescriptor descriptor = new NotifyDescriptor.Message(
                    "<html>Found zero-magnitude axis for <b>direction</b> vector, reset to 0 0 -1</html>", NotifyDescriptor.WARNING_MESSAGE);
            DialogDisplayer.getDefault().notify(descriptor);
            directionXTF.setText("0");
            directionYTF.setText("0");
            directionZTF.setText("-1");
        }
        else
        {
            directionXTF.setText(fiveDigitFormat.format(x / normalizationFactor));
            directionYTF.setText(fiveDigitFormat.format(y / normalizationFactor));
            directionZTF.setText(fiveDigitFormat.format(z / normalizationFactor));
        }
  }//GEN-LAST:event_normalizeButtonActionPerformed

    private void nearDistanceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearDistanceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nearDistanceTFActionPerformed

    private void farDistanceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farDistanceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farDistanceTFActionPerformed

    private void fieldOfViewTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfViewTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfViewTFActionPerformed

    private void colorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooserActionPerformed
    Color c = colorChooser.getColor();                                                 
    color0TF.setText(formatDecimal((float)c.getRed()/255));
    color1TF.setText(formatDecimal((float)c.getGreen()/255));
    color2TF.setText(formatDecimal((float)c.getBlue()/255));
    }//GEN-LAST:event_colorChooserActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ambientIntensityTF;
    private javax.swing.JLabel ambientLabel;
    private javax.swing.JLabel bLabel;
    private org.web3d.x3d.palette.BetterJTextField color0TF;
    private org.web3d.x3d.palette.BetterJTextField color1TF;
    private org.web3d.x3d.palette.BetterJTextField color2TF;
    private net.java.dev.colorchooser.ColorChooser colorChooser;
    private javax.swing.JLabel colorLabel;
    private org.web3d.x3d.palette.items.DEFUSEpanel dEFUSEpanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel directionLabel;
    private javax.swing.JTextField directionXTF;
    private javax.swing.JTextField directionYTF;
    private javax.swing.JTextField directionZTF;
    private javax.swing.JLabel eventsLabel;
    private javax.swing.JLabel farDistanceLabel;
    private javax.swing.JTextField farDistanceTF;
    private javax.swing.JLabel fieldOfViewLabel;
    private javax.swing.JTextField fieldOfViewTF;
    private javax.swing.JLabel gLabel;
    private javax.swing.JCheckBox globalCB;
    private javax.swing.JLabel globalLabel;
    private javax.swing.JPanel hintPanel;
    private javax.swing.JLabel intensityLabel;
    private javax.swing.JTextField intensityTF;
    private javax.swing.JLabel nearDistanceLabel;
    private javax.swing.JTextField nearDistanceTF;
    private javax.swing.JButton normalizeButton;
    private javax.swing.JCheckBox onCB;
    private javax.swing.JLabel onLabel;
    private javax.swing.JLabel rLabel;
    private javax.swing.JLabel shadowIntensityLabel;
    private javax.swing.JTextField shadowIntensityTF;
    private javax.swing.JCheckBox shadowsCB;
    private javax.swing.JLabel shadowsLabel;
    // End of variables declaration//GEN-END:variables

   @Override
   public String getNameKey()
  {
    return "NAME_X3D_TEXTUREPROJECTOR";
  }
   @Override
   public void unloadInput()
   {
     unLoadDEFUSE();
     
    textureProjector.setAmbientIntensity(ambientIntensityTF.getText().trim());
    
    textureProjector.setColor0(color0TF.getText().trim());
    textureProjector.setColor1(color1TF.getText().trim());
    textureProjector.setColor2(color2TF.getText().trim());
    
    textureProjector.setGlobal(globalCB.isSelected());
    
    textureProjector.setDescription(descriptionTextField.getText().trim());
    textureProjector.setIntensity(intensityTF.getText().trim());
    textureProjector.setIntensity(intensityTF.getText().trim());

    if (directionXTF.getText().equals("0") && directionYTF.getText().equals("0") && directionZTF.getText().equals("0")) normalizeButton.doClick();
    textureProjector.setDirectionX(directionXTF.getText().trim());
    textureProjector.setDirectionY(directionYTF.getText().trim());
    textureProjector.setDirectionZ(directionZTF.getText().trim());
    
    textureProjector.setOn(onCB.isSelected());
    
    textureProjector.setShadows(shadowsCB.isSelected());
    textureProjector.setShadowIntensity(shadowIntensityTF.getText().trim());
   }
}
