/*
 * PduHeaderDisplayPanel.java
 *
 * Created on October 26, 2008, 2:45 PM
 */
package org.web3d.x3d.dis.playerrecorder;

import edu.nps.moves.dis7.pdus.Pdu;
import edu.nps.moves.dis7.pdus.PduBase;

import org.openide.util.NbBundle;

/**
 *
 * @author  mike
 */
public class PduHeaderDisplayPanel extends javax.swing.JPanel
{
  /** Creates new form PduHeaderDisplayPanel */
  public PduHeaderDisplayPanel()
  {
    initComponents();
  }
  private boolean active = false;

  public void setData(Pdu pdu)
  {
         exerciseIDTF.setText("" + pdu.getExerciseID());
            paddingTF.setText("" + ((PduBase)pdu).getPadding());
          pduLengthTF.setText("" + pdu.getLength());
            pduTypeTF.setText(pdu.getPduType().getDescription());
     protocolFamilyTF.setText(pdu.getProtocolFamily().getDescription());
    protocolVersionTF.setText(pdu.getProtocolVersion().getDescription());
          timeStampTF.setText("" + pdu.getTimestamp());

    // TODO:  strategy to update field colors
//    if (!active) updateFieldColors();
  }
  
  private void updateFieldColors()
  {
       exerciseIDTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
          paddingTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
        pduLengthTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
          pduTypeTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
       protocolFamilyTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
      protocolVersionTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);
        timeStampTF.setForeground(DISPlayerRecorderPanel.ACTIVE_COLOR);

      active = true;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        timeStampLabel = new javax.swing.JLabel();
        timeStampTF = new javax.swing.JTextField();
        exerciseIdLabel = new javax.swing.JLabel();
        exerciseIDTF = new javax.swing.JTextField();
        pduLengthLabel = new javax.swing.JLabel();
        pduLengthTF = new javax.swing.JTextField();
        pduTypeLabel = new javax.swing.JLabel();
        pduTypeTF = new javax.swing.JTextField();
        protocolVersionLabel = new javax.swing.JLabel();
        protocolVersionTF = new javax.swing.JTextField();
        protocolFamilyLabel = new javax.swing.JLabel();
        protocolFamilyTF = new javax.swing.JTextField();
        paddingLabel = new javax.swing.JLabel();
        paddingTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        timeStampLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        timeStampLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.timeStampLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 3);
        add(timeStampLabel, gridBagConstraints);

        timeStampTF.setColumns(3);
        timeStampTF.setEditable(false);
        timeStampTF.setForeground(new java.awt.Color(0, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(timeStampTF, gridBagConstraints);

        exerciseIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        exerciseIdLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.exerciseIdLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(exerciseIdLabel, gridBagConstraints);

        exerciseIDTF.setColumns(3);
        exerciseIDTF.setEditable(false);
        exerciseIDTF.setForeground(new java.awt.Color(0, 102, 102));
        exerciseIDTF.setMinimumSize(new java.awt.Dimension(40, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(exerciseIDTF, gridBagConstraints);

        pduLengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pduLengthLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.pduLengthLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(pduLengthLabel, gridBagConstraints);

        pduLengthTF.setColumns(3);
        pduLengthTF.setEditable(false);
        pduLengthTF.setForeground(new java.awt.Color(0, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(pduLengthTF, gridBagConstraints);

        pduTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pduTypeLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.pduTypeLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 3);
        add(pduTypeLabel, gridBagConstraints);

        pduTypeTF.setColumns(3);
        pduTypeTF.setEditable(false);
        pduTypeTF.setForeground(new java.awt.Color(0, 102, 102));
        pduTypeTF.setMinimumSize(new java.awt.Dimension(40, 22));
        pduTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pduTypeTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(pduTypeTF, gridBagConstraints);

        protocolVersionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        protocolVersionLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.protocolVersionLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(protocolVersionLabel, gridBagConstraints);

        protocolVersionTF.setColumns(3);
        protocolVersionTF.setEditable(false);
        protocolVersionTF.setForeground(new java.awt.Color(0, 102, 102));
        protocolVersionTF.setMinimumSize(new java.awt.Dimension(40, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(protocolVersionTF, gridBagConstraints);

        protocolFamilyLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        protocolFamilyLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.protocolFamilyLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(protocolFamilyLabel, gridBagConstraints);

        protocolFamilyTF.setColumns(3);
        protocolFamilyTF.setEditable(false);
        protocolFamilyTF.setForeground(new java.awt.Color(0, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.333;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(protocolFamilyTF, gridBagConstraints);

        paddingLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        paddingLabel.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.paddingLabel.text")); // NOI18N
        paddingLabel.setToolTipText(org.openide.util.NbBundle.getMessage(PduHeaderDisplayPanel.class, "PduHeaderDisplayPanel.paddingLabel.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(paddingLabel, gridBagConstraints);

        paddingTF.setColumns(3);
        paddingTF.setEditable(false);
        paddingTF.setForeground(new java.awt.Color(0, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(paddingTF, gridBagConstraints);

        jLabel1.setText(NbBundle.getMessage(getClass(), "PduHeaderDisplayPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void pduTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pduTypeTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pduTypeTFActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField exerciseIDTF;
    private javax.swing.JLabel exerciseIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel paddingLabel;
    public javax.swing.JTextField paddingTF;
    private javax.swing.JLabel pduLengthLabel;
    public javax.swing.JTextField pduLengthTF;
    private javax.swing.JLabel pduTypeLabel;
    public javax.swing.JTextField pduTypeTF;
    private javax.swing.JLabel protocolFamilyLabel;
    public javax.swing.JTextField protocolFamilyTF;
    private javax.swing.JLabel protocolVersionLabel;
    public javax.swing.JTextField protocolVersionTF;
    private javax.swing.JLabel timeStampLabel;
    public javax.swing.JTextField timeStampTF;
    // End of variables declaration//GEN-END:variables
}
